### ISSUE TITLE
text editing

### ISSUE THREAD

**Issue by troy-lamerton** [robaho/seashore#107]
When I have finished writing text, it is added to the layer as pixels.

A few moments later I want to change the text, but can't. So I rectangle select it, delete, create new text.

We should be able to edit text after it is created. So adding a new text would add a new layer.

**Comment by robaho** [comment]
Seashore doesn't support "text layers". The best solution is to create a new layer first. Add the text. The 'condense the layer to content' - then position the layer.

I've thought about adding "text layers" but they would be handled completely different than the raster layers, and I'm not sure the users would like that.

**Comment by troy-lamerton** [comment]
> I've thought about adding "text layers" but they would be handled completely different than the raster layers, and I'm not sure the users would like that.

Do you have any data on what users would like when it comes to text?

Consider what a user is used to. Users might have no expectation, or come from Paint, Photoshop, GIMP, or something else?

### Expectations based on previous tool
Paint (windows 10): ? (dont remember)
Photoshop: text layers
GIMP: text layers
No expectations: no preference

Of course, changes to text handling would need to be intuitive like rest of seashore.

**Comment by robaho** [comment]
The early versions of GIMP (and I think Photoshop) did not have text layers. I am very wary of feature creep which usually leads to increased complexity in both the code and the user interface.

I think that maybe a first pass feature might be a check-box to auto-create a new layer (and float) when adding the text - not quite a text layer but it definitely simplifies the workflow.

And maybe a drop-down to select previously entered text to avoid repeated typing.

**Comment by robaho** [comment]
fixed in 2.5.3 - added ability to always create a New Layer when adding text. This greatly simplifies things.

Also, I discovered that in order to do "high quality" text it needs to anti-alias with the bottom layer, so using a new layer (or a text layer if we had them), would be more difficult

**Comment by troy-lamerton** [comment]
![image](https://user-images.githubusercontent.com/13446008/73046554-e527b500-3e72-11ea-9f68-93a5ba162b86.png)

It works good so far, I'll make a new issue if needed.
