### ISSUE TITLE
Won't open images created by Nikon D850

### ISSUE THREAD

**Issue by HibHalverson** [robaho/seashore#117]
Seashore will not open .jpg images created by a Nikon D850, however it will open .jpg images created by either a Nikon D3 or a Nikon D5.

Any ideas.

**Comment by robaho** [comment]
Please attach an image that doesn't work here and I'll take a look.

**Comment by HibHalverson** [comment]
Robert-

I'll add that I get the same error on both my Macs, each of which is running OS 10.14.6. Both Photoshop CS6 and Graphic Converter 10 will open the images.

A screen shot of the error message is attached.

Regards,

Hib Halverson
General Manager
Shark Communications

**Comment by HibHalverson** [comment]
Robert-

I tried to email you some images but the post bounced because the attached files were too large.

I will try uploading the images to Drop Box.

I  attached three images, just as they came out of the cameras. DSC_4374 was shot by a D850. DSC_1592 was shot by a D5. DSC_was shot by the a D3.

So far, none of the .jpg images I have shot with he D850 can be opened by Seashore.


Regards,

Hib Halverson
General Manager
Shark Communications

**Comment by HibHalverson** [comment]
Hi there,

Hib Halverson (finspeed@netmotive.net) invited you to for Robert .

 View on Dropbox[1] 
 
Join Dropbox to do more with shared files like this

   Stay organized
  Keep files and cloud content—like Google Docs—in one space.         Work together
  Stay in touch with your team with the tools you use every day alongside your files.         Find it fast
  See relevant files right when you need them.    

[1]: https://www.dropbox.com/l/scl/AADI9bYM28ueAwxcRaM6Oy88rGQHe75KfG4

**Comment by robaho** [comment]
Hi Hib,

The reason the image can't be loaded is that it is too large. The current software has a limitation of 8192 pixels h/v.

I have upped this to 16k in each direction for version 2.5.7 (which in RGBA8888 is about 1GB).

Beyond that it gets a little more difficult as internally many of the memory allocations, and file offsets are "ints". It is only the road-map to support these very large images, but to be honest many of the internal procedures and structures would need to change - a lot of work :)

**Comment by robaho** [comment]
fixed in version 2.5.7 by increasing max image dimensions. Issue #118 has been submitted to handle even larger images.

**Comment by robaho** [comment]
as a note, using very large images like this should only be done in most cases if going to print. The software is going to perform much worse as the data exponentially increases - it also consumes a lot of space on the camera/disk :)

**Comment by HibHalverson** [comment]
Robert-

Where can I get v2.5.7?

I can only find 2.5.6 listed on SourceForge.


Regards,

Hib Halverson
General Manager
Shark Communications

**Comment by HibHalverson** [comment]
Robert-

> On Feb 14, 2020, at 4:04 PM, robert engels <notifications@github.com> wrote:
> 
> as a note, using very large images like this should only be done in most cases if going to print.
> 
That's what I do for some of my clients. I'm an automotive writer and I shoot most of my own imagery. Some of the media I work for are print magazines.



Regards,

Hib Halverson
General Manager
Shark Communications

**Comment by robaho** [comment]
It is now available in the App Store - I haven't uploaded to github 'releases' yet - probably not until tomorrow.

Sourceforge no longer has the updated binaries - they are only provided here and on the App Store.

As an aside, if you don't have a philosophical disagreement with the App Store - that is by far the easiest and simplest way to get Seashore.

**Comment by HibHalverson** [comment]
> On Feb 14, 2020, at 4:57 PM, robert engels <notifications@github.com> wrote:
> 
> It is now available in the App Store - I haven't uploaded to github 'releases' yet - probably not until tomorrow.
> 

> Sourceforge no longer has the updated binaries - they are only provided here and on the App Store.
> 
> As an aside, if you don't have a philosophical disagreement with the App Store - that is by far the easiest and simplest way to get Seashore.
> 
I'm ok with AppStore but it's stil at 2.5.6 which I just downloaded.

 I'll check Github tomorrow.

Thanks, Robert.




Regards,

Hib Halverson
General Manager
Shark Communications

**Comment by robaho** [comment]
The App Store lags a bit unless you refresh. I am going to upload to github now.

**Comment by HibHalverson** [comment]
Hey there Robert-

> On Feb 14, 2020, at 6:58 PM, robert engels <notifications@github.com> wrote:
> 
> The App Store lags a bit unless you refresh. I am going to upload to github now.

App Store had the new version this morning.

I appreciate your prompt responses. 

I've been looking for an image program which can replace Photoshop CS6, which is a 32-bit application and because I'm not enamored with Adobe's subscription model for current versions of P'shop. Seashore is on my list.



Regards,

Hib Halverson
General Manager
Shark Communications

**Comment by robaho** [comment]
Don’t forget to leave your positive review on the App Store if it works out for you!

**Comment by HibHalverson** [comment]
Robert-

> On Feb 15, 2020, at 10:05 AM, robert engels <notifications@github.com> wrote:
> 
> Don’t forget to leave your positive review on the App Store if it works out for you!

I need to spend more time learning the program. It's a bit different than Photoshop.







Regards,

Hib Halverson
General Manager
Shark Communications

**Comment by robaho** [comment]
I’d really like to hear your thoughts about things that you found difficult easy etc. I’m always looking to make the program better and that sort of feedback is what I need thanks

**Comment by HibHalverson** [comment]
Hey Robert-

> On Feb 15, 2020, at 11:30 AM, robert engels <notifications@github.com> wrote:
> 
> I’d really like to hear your thoughts about things that you found difficult easy etc. I’m always looking to make the program better and that sort of feedback is what I need thanks

I don't have anything for you right now, but I'll keep in touch and give input when I have something useful.



Regards,

Hib Halverson
General Manager
Shark Communications
