### ISSUE TITLE
How do you resize an image proportionally?

### ISSUE THREAD

**Issue by Navy-Brat** [robaho/seashore#119]
I'm so sorry, but I'm having trouble resizing images proportionally.

As I understand it, you choose "Scale Image" from the "Image" menu, making sure that the "Keep Proportions" checkbox is checked before you click on the "Scale" button on the bottom to resize the image. My problem is, I must be doing it wrong because I can never get it to resize proportionally.

How do you resize an image proportionally?

As always, thank you.

**Comment by robaho** [comment]
No need to be sorry. That's exactly the way you do it. Can you show a screen shot, before/after of what is not working?

If you change the % (the easiest way), and the 'Keep Proportions' is checked, both the percentages should be the same, and the width & height should change accordingly.

I just tested this and everything worked as I would expect.

**Comment by robaho** [comment]
You can also scale and rotate the a layer - not the entire image.

I am going to close this, as I am pretty sure it works.

**Comment by Navy-Brat** [comment]
Thank you so much for the nice help.

I found out what I was failing to do was not clicking in the other dimension box.

To be clearer, whether you scale by percentage or by pixel size, if you don't click your mouse or trackpad in the opposing dimension, it won't scale when you click the "Scale" button.

For example, if you change the percentage in the "Horizontal" box and not click in the "Vertical" box before clicking the "Scale" button, it won't scale. But if you do click in "Vertical" box before clicking the "Scale" button, it will scale. The same holds true for the "Height" and "Width" boxes. And, as you say, as always make sure that you've got the "Keep proportions" check box checked.

Thank you so much for the nice and speedy help.

**Comment by robaho** [comment]
I've noticed that in the past - and I guess it just became "knowledge" to make sure the values are posted. I am going to file another issue to "force the edits" prior to "processing OK" to avoid this for others.
