### ISSUE TITLE
How do you change the canvas size?

### ISSUE THREAD

**Issue by Navy-Brat** [robaho/seashore#120]
How do you change the canvas size in Seashore 2.5.7?

In Adobe PhotoShop Elements and Pixelmator, you could change the canvas size by choosing "Canvas Size" from the "Image" menu, but in Seashore, I couldn't find it in the "Help" menu and the Seashore Guide was very confusing. I'm so sorry.

**Comment by robaho** [comment]
You use Image -> Image Boundaries. The width/height is the size of the image. You can try experimenting - if you increase the height by 10, you should see 5 in the top and bottom offsets as it tries to center the image in the new size.

You can drag the layers around to reposition in your canvas after resizing.

**Comment by Navy-Brat** [comment]
Again, thank you.

I found out that not only can you expand the canvas just by plugging in numbers, but you can also cut into the image by plugging in negative numbers.

I have one more question. What does the "Set boundaries relative to content" checkbox do in the "Image Boundaries" option of the "Image" menu?

**Comment by robaho** [comment]
"relative to content" means the borders of the image are changed to account for purely transparent pixels - shrinking the borders to remove them. I have attached am image (needed to zip to attach) to demonstrate. Open it, and use 'image boundaries' click the 'content relative' and 'Set' and see how it works.

[sample.zip](https://github.com/robaho/seashore/files/4241790/sample.zip)
