### ISSUE TITLE
Feedback: initial new image dialog, open recent unexpected behaviour

### ISSUE THREAD

**Issue by aaronclawrence** [robaho/seashore#133]
Hello, and thank you very much for Seashore.
I have one minor suggestion: on the initial New Image dialog, the behaviour of the Open Recent dropdown is a little unexpected or unintuitive to me.
Traditionally, a dropdown does not take effect immediately on selecting and item, you would select something and then click a button to take effect.

So I usually click on the dropdown item, expecting to then have to click the green button next to it. But of course it opens immediately.

It's not a big deal but just unexpected.

I'm sorry I'm. not sure what would be better behaviour; maybe the Create button could turn into Open instead. Or perhaps a tabbed dialog with recent files and an open button would work.

Thanks for listening.

**Comment by robaho** [comment]
You're welcome. Thank you for the feedback. I agree that it may not be the most intuitive - using the File -> Open Recent is certainly more standard. You can disable the 'New Dialog' automatically opening in the Seashore preferences.
