### ISSUE TITLE
No crop bar or buttons.

### ISSUE THREAD

**Issue by Gewurztraminer** [robaho/seashore#138]
Crop does not produce crop toolbar. Deleted and installed new. Still no crop bar. Can't find plist, nothin gin Application Support.

**Comment by robaho** [comment]
Can you attach a screenshot highlighting what you mean? This is no 'crop toolbar' - there is a 'crop tool'. When selected, you can drag to select the area to crop, use the options in the 'options bar', and then 'crop layer' or 'crop image'.

Did you read the guide?

**Comment by robaho** [comment]
Here is a couple of screen shots:

![image](https://user-images.githubusercontent.com/4958833/99625684-5f26bd00-29f6-11eb-9186-8d7d95a84f51.png)
![image](https://user-images.githubusercontent.com/4958833/99625761-89787a80-29f6-11eb-86d2-a2ed8a191593.png)

**Comment by Gewurztraminer** [comment]
OK, found it. To clarify, Crop button was there, but not Crop Image/ Crop Layer as there was no toolbar. Hide Options was asserted, but Show Options produced only a sliver of grey chrome, no buttons. Turning off rulers and reloading fixed it. I can't reproduce, both work together now. I think it's a window resizing issue.

**Comment by robaho** [comment]
Not sure hiding options even makes sense - I guess if you want lots of screen real estate and know all of the keyboard shortcuts. I may remove that option. 

I’m not sure how you had it hidden as the default should be to show it.

**Comment by Gewurztraminer** [comment]
I've never intentionally used Hide Option - it was probably a cat on the keyboard - but after I'd found it the options toolbar was only a thin stripe - no buttons. Seashore is my go-to image editor, use it every day because it's so fast. The only other insignificant but weird thing is no name in Force Quit (This machine is High Sierra. Can't say I've noticed it on late OS).
![Screen Shot 2020-11-22 at 7 39 10 PM](https://user-images.githubusercontent.com/5916105/99921834-212ddf80-2cfb-11eb-8d1e-f8c522a1e563.png)
