### ISSUE TITLE
export window won't load or does but window incomplete

### ISSUE THREAD

**Issue by seeingears** [robaho/seashore#141]
I'm a total beginner and I have just downloaded Seashore from the app store to see if I can do collages with it. I imported a jpg, erased the background and have succeeded in saving the project. I've flattened the layers and want to export. Pressing "Export..." does either nothing, or when the dialog box randomly appears, the part which should say "Options" is squished and transparent - so I may only export as an XCF. 
That's not right is it?
![squishedDialog](https://user-images.githubusercontent.com/76452793/102820009-70376500-43cc-11eb-830e-ce1ec2e10a15.jpg)

**Comment by robaho** [comment]
No, that does not look correct at all. Which version of OSX are you using? Do you get the same behavior with 'Save As' (that may be a work-around).

Here is screenshot for reference:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/4958833/103026468-a0404e80-4519-11eb-8c5a-8651bc45eadb.png">

**Comment by seeingears** [comment]
Thanks for the swift reply robaho. Actually I encounter a similar problem with "Save As," sometimes it will open a dialog box but mostly not. I'm using OS X 10.9.5 - it's an old MacBook Pro from 2010 - can't afford to upgrade right now. I thought this would be compatible? Should I look for an older version of Seashore perhaps?

**Comment by robaho** [comment]
Give me the weekend to test with that OS X version.

**Comment by seeingears** [comment]
That's exceptionally kind, but please there's no huge rush, it's Christmas after all :) Thank you for looking into this for me. Of what I've used of Seashore so far it's pretty impressive.

**Comment by robaho** [comment]
I was able to reproduce - I'll work on a fix. In the meantime, I think you can make it work by pressing the 'small portion of the arrow' that is visible - you should see the drop down - and be able to chose the correct format although you won't be able to see what you chose.

**Comment by robaho** [comment]
fixed in 2.5.10
