### ISSUE TITLE
Missing file after cloning to Git Desktop

### ISSUE THREAD

**Issue by SimonKravis** [robaho/seashore#143]
When I clone the project and try to build it in Xcode I get the message below. How do I fix it?

StripNIB /Users/robertengels/seashore/Seashore/resources/PrintPanelAccessory.nib (in target 'Seashore' from project 'Seashore')
    cd /Users/apple/Documents/GitHub/seashore/Seashore
    export XCODE_DEVELOPER_USR_PATH\=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /Users/apple/Library/Developer/Xcode/DerivedData/seashore-buienfengmwzevabtfmatqtrdefq/Build/Products/Release/Seashore.app/Contents/Resources/PrintPanelAccessory.nib --output-format human-readable-text /Users/robertengels/seashore/Seashore/resources/PrintPanelAccessory.nib

error: Build input file cannot be found: '/Users/robertengels/seashore/Seashore/resources/PrintPanelAccessory.nib' (in target 'Seashore' from project 'Seashore')

**Comment by robaho** [comment]
The last release was missing some commits. If you clone now you should be OK.
