### ISSUE TITLE
Missing file GIMPCore.h

### ISSUE THREAD

**Issue by SimonKravis** [robaho/seashore#144]
#import <GIMPCore/GIMPCore.h> in /Users/apple/Documents/GitHub/seashore/Seashore/source/tool/gradientTool.m fails with missing file with clone done just now

**Comment by robaho** [comment]
You need to use the workspace included, and probably build with XCode 12.3

I cloned a new copy and it built fine. Attaching the build log.

[Build Seashore_2020-12-30T18-47-05.txt](https://github.com/robaho/seashore/files/5756129/Build.Seashore_2020-12-30T18-47-05.txt)

**Comment by SimonKravis** [comment]
Thanks  for your prompt replies.

 

I’m new to Mac development – if  open the file seashore.xcworkspace with XCode  it shows Build CMYK: Succeeded but the Product->Run option is greyed out. How can I run seashore within XCode?

 

If I open seashore.xcodeproj then I get the error regarding  GIMPCore.h

 

Regards

 

Simon Kravis

**Comment by robaho** [comment]
You need to select the Seashore scheme. You can also read the buildnotes.txt for building from the command line. Sorry, but I don't have time to support build/training issues.
