### ISSUE TITLE
Unable to turn off image smoothing/anti-aliasing

### ISSUE THREAD

**Issue by janprzy** [robaho/seashore#146]
I am trying to edit a 32x32 image in Seashore version 2.5.10. However, Seashore applies anti-aliasing, making everything appear blurred. Turning off the "Use image smoothing" setting has no effect.

This definitely worked a year ago, but I tried going back as far as version 2.5.6, that didn't fix it.

Maybe my settings are corrupted, but reinstalling the app and/or deleting `~/Library/Containers/app.seashore` did not help either.

Example: 
![Bildschirmfoto 2021-02-06 um 15 06 27](https://user-images.githubusercontent.com/41625296/107120434-e6652d80-688d-11eb-910c-210c49fccb2f.png)

**Comment by robaho** [comment]
I've been looking into this, and I think it may be a OSX bug on Retina displays. I've attempted several work-arounds but can't seem to fix it - but I'm still working on it.

**Comment by janprzy** [comment]
Thanks! I'm not sure if the retina display could be to blame. While my Mac's internal display is retina, this also happens on my external monitor, which is not.

**Comment by janprzy** [comment]
I tried on a different Mac that has no retina display, it worked there. However, that Mac is running Catalina instead of Big Sur, maybe that's the reason. That would also explain why everything worked fine on my retina-equipped Mac a year ago.

**Comment by robaho** [comment]
Yea, I think it is a combo of Big Sur and Retina. I made some changes to make it work, but performance was terrible. I am going to file a bug with Apple.

**Comment by janprzy** [comment]
Alright, thanks for the effort!

**Comment by robaho** [comment]
fixed in 3.01
