### ISSUE TITLE
Background colour

### ISSUE THREAD

**Issue by markbullen54** [robaho/seashore#149]
I have just started using Seashore and have a simple question: how do I change the colour of a background layer? I created the layer, I selected the foreground/background tool to bring up the color picker, I selected a color, then selected the bucket tool to flood the layer but nothing happens. Must be missing something obvious (or not so obvious).

Thanks.

**Comment by robaho** [comment]
Did you pick the foreground color? When you are editing a layer - you are normally changing a layers "foreground". The only time "background" is used is when you are erasing within a layer. So 'fill' uses the 'foreground' color to fill.

Also, did you read the guide? It is available under the Help menu.

**Comment by markbullen54** [comment]
Ok, that explains it. I assumed it was the background colour because the layer is in the background.
And, yes I did read the guide.
Thanks agan.

**Comment by robaho** [comment]
“background” is relative when using “layers”. As you can have many layers and reorder them. 

TBH “background” is probably a bad name - it should be called “erase color” so I agree it can be confusing.
