### ISSUE TITLE
codesign warning

### ISSUE THREAD

**Issue by grylem** [robaho/seashore#151]
Hi
some applications for signature checking show warnings like "bundle format is ambiguous (could be app or framework)" for frameworks.

You can reproduce it with codesign utility
codesign -f -s -  GIMPCore.framework
GIMPCore.framework: bundle format is ambiguous (could be app or framework)

Regards.

**Comment by robaho** [comment]
Using 

> codesign -v GIMPCore.framework

I get not errors in the 3.02 release - so I am pretty sure the signatures are correct.
