### ISSUE TITLE
New from Pasteboard doesn't open any window

### ISSUE THREAD

**Issue by jlseach** [robaho/seashore#153]
Hello,

after copying a bitmap from Inkscape, the functionality "New from Pasteboard" inside SeaShore doesn't open any window.
But when I close SeaShore it tells me that I have many non saved documents which are empty

**Comment by robaho** [comment]
I can't really test with Inkscape. If you open the bitmap in preview, and do a 'copy' there, can you paste as new in Seashore?

**Comment by robaho** [comment]
Closing, as I cannot reproduce. Please re-open with additional details if possible.
