### ISSUE TITLE
SEASHORE LAGGING 

### ISSUE THREAD

**Issue by DDevDevonne** [robaho/seashore#154]
This program is amazing but at some time its reporting on Mac an issue that is taking too much large app space

<img width="1280" alt="Screenshot 2022-05-19 at 2 09 31 PM" src="https://user-images.githubusercontent.com/105858371/169280846-ffdc3524-66e9-4429-8692-ed161ec2838b.png">

**Comment by DDevDevonne** [comment]
HELPPP

**Comment by DDevDevonne** [comment]
After that problem occurs its opens up again but it didn't saved what u did

**Comment by robaho** [comment]
There is a major update this is going to be posted soon. Does this happen on all files or just some?

**Comment by robaho** [comment]
Is it possible for you to send me a private message - or post here - the image file you were working with?

**Comment by DDevDevonne** [comment]
Hello there its is the error. And all the changes I did on the file, they dissapear …



DDevDimitrova 

On Friday, May 20, 2022, 7:37 PM, Desislava Dimitrova ***@***.***> wrote:

Im working on .png file. I will Try to screenshot it whenever the error appears. Probably tomorrow Cuz Im going to work.


DDevDimitrova 

On Friday, May 20, 2022, 3:25 AM, robert engels ***@***.***> wrote:




Is it possible for you to send me a private message - or post here - the image file you were working with?

**Comment by robaho** [comment]
This should be addressed in 3.01. Also, when working with large images set the number of undos to something reasonable to reduce memory usage.

**Comment by DDevDevonne** [comment]
any files ….


DDevDimitrova 

On Thursday, May 19, 2022, 7:59 PM, robert engels ***@***.***> wrote:




There is a major update this is going to be posted soon. Does this happen on all files or just some?

**Comment by DDevDevonne** [comment]
Im working on .png file. I will Try to screenshot it whenever the error appears. Probably tomorrow Cuz Im going to work.


DDevDimitrova 

On Friday, May 20, 2022, 3:25 AM, robert engels ***@***.***> wrote:




Is it possible for you to send me a private message - or post here - the image file you were working with?

**Comment by DDevDevonne** [comment]
Thank you for the help, but I'm not longer using  the program. I finished, the project I did. If I have problems in future I will text you again!a a great day :)

DDevDimitrova 

On Tuesday, October 11, 2022, 2:21 PM, robert engels ***@***.***> wrote:




Reopened #154.

**Comment by robaho** [comment]
Can you tell me what the comment 

any files…

means. Are you staying that on version 3.9 any file you open lags? But you were able to use it to finish your project?

thanks for your help I appreciate it.

**Comment by DDevDevonne** [comment]
Any files ment .jpg ; .png; I my project on another program. 
The version was last one, till the time we correspond last time, I do not remember the number. Have a great day!

DDevDimitrova 

On Tuesday, October 11, 2022, 2:47 PM, robert engels ***@***.***> wrote:




Can you tell me what the comment

any files…

means. Are you staying that on version 3.9 any file you open lags? But you were able to use it to finish your project?

thanks for your help I appreciate it.

**Comment by robaho** [comment]
Closing. I don’t understand what the problem was or the version so there’s not much I can do. Bummer.
