### ISSUE TITLE
3.0 crash on launch

### ISSUE THREAD

**Issue by robinson-heath** [robaho/seashore#155]
Updated to 3.0 on Mac this morning (Sytsem Prefs/Updates/App Store) and it crashed on launch. I can't get it to open at all.

MacBook Pro (16-inch, 2019)
2.6 GHz 6-Core Intel Core i7
16 GB 2667 MHz DDR4
AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB
Mac OS 10.15.7

**Comment by robinson-heath** [comment]
Crash report attached
[Seashore_2022-07-01-115213_batman.crash.zip](https://github.com/robaho/seashore/files/9029543/Seashore_2022-07-01-115213_batman.crash.zip)

**Comment by robaho** [comment]
Sorry about that - I pulled the release almost immediately (but for another issue). It seems that 10.15.7 is broken when running plugins compiled for a later release. I will need to adjust some build parameters. Thanks for reporting it.

**Comment by robaho** [comment]
Ends up it has been so long since the last release, I forgot how to build it properly. It should be up today.

Fixed in 3.01
