### ISSUE TITLE
Image  Menu , Image Size (Boundaries) NOT showing former Top, Bottom, Left, Right editing parameters

### ISSUE THREAD

**Issue by vortexau-jk** [robaho/seashore#163]
Just a few days ago (after "**Remove this banner by supporting the Seashore Project.**" header appeared) and even since I bought **ONE SUPPORT** and was informed "Your purchase was successful" --- the **IMAGE** Menu / **IMAGE Size** (formerly **Boundaries**) only shows IMAGE Size **Width** & **Height** adjustable parameters,  with No direction changing T,B,L,R choices any more.

Up until just those few days ago **this menu** displayed the **Figure 1** - The image boundaries sheet as displayed on **page 36** of the **SEASHORE GUIDE**.pdf !  This boundaries sheet no longer appears- just what was possibly a simple WIDTH and HEIGHT entry box.

Currently: Version 3.02 (2022070102) yesterday, or **3.03** (2022070401) The later version displayed today!

Host Mac: **Mac Pro 6.1** (Late 2013) Proc: 3.5 GHz 6.Core Intel Xeon E5
		Memory 32 GB 1866 MHz DDR3
Running:   **macOS Monterey** Ver 12.4
![Screen Shot 2022-07-10 at 6 37 47 pm](https://user-images.githubusercontent.com/109019093/178137608-b23a2871-fc78-49e4-9d2e-fcb12adbde40.png)

**Comment by robaho** [comment]
Thank you for supporting Seashore! The 'boundaries' option was removed in version 3.0+ since it seemed to cause confusion with users. The 'Adjust layer positions proportionally' covers most of the use cases I am aware of.

Can you describe your use-case for this feature?

**Comment by vortexau-jk** [comment]
Hi Robert,

I tend to use that (this) Boundaries TOP, LEFT, BOTTOM, RIGHT, Feature very often, up to now. Let me explain . . ⬇️(jump to Mac use half-way down email)

I have been a “micro”computer user for some 39 years (beginning at age 33) now, but as an artist really got into the graphical image (on 16 - 32 bit hardware) in 1988 with the first of my FIVE Amiga computers. Initially having a Hard Drive was out of my price range so I accrued more than 200 x 880k 3.5” floppy disks containing my graphic “productions” prior to being able to upgrade to a A2000HD system in 1990. This machine came with a 49MB SCSI HD . Commodore had a habit of procuring the smallest HDs for their thus-equipped hardware . . . . smallest owned was a later A600HD with a 30MB IDE drive.

THIS A2000HD served me well, being itself successively upgraded over the next decade (from 1Mb RAM to 64Mb. From motorola 68000 7.09379 MHz [on PAL systems] to motorola 68060 at 50 MHz . . . . when Apple’s fastest pre-PPC Macintosh model was their Quantra with its 68040 clocked at 25 MHz.
When I “upgraded” the Amiga native graphics with a Picasso II+ board ( http://amiga.resource.cx/exp/picasso2plus <http://amiga.resource.cx/exp/picasso2plus> ) I moved up to working on 24bit colour images at 800 x 600 pixel sizes (a limitation of 2MB boards), over the former 640 x 512 (PAL) pixel 16 colour HiRes images which were the limit in native graphics.  {Amigas came in NTSC models with 480 pixels high too}

I even had to use various ways to “enlarge”  640 x 512 pixel 24bit Frame-Grabs (from SVideo / and PAL television) to utilise the extra 160 horizontal pixels, and the extra 88 vertical pixels available on my 19” Samsung multi-scan CRT. 1600 x 1200 images had severe colour range limits. The Amiga could output multiple different “screens” at different pixel resolutions . . . and “screen” displays could be Mouse Dragged UP & DOWN over each other with different resolutions visible at the “display “border”! . . . try doing that today?

With the Picasso II+’s 24bit capability, I made much use of the application TVPaint Junior which opened up graphical operations un-available with the earlier DeluxePaint series and PersonalPaint versions, which had their limits at 16 colours, or HAM; a 12bit colour hardware shortcut. ( https://www.tvpaint.com/History.php <https://www.tvpaint.com/History.php> )

- - The current TVPaint 11.5 Standard Edition retails at 810.1 AUD [ 500 € ] (which is really highly priced for a 72 Y.O. retired computer artist!)
Cash Flow limitations usually force me to use 9 - 11 Y.O. S/H Macs! . . . hence my current Mac Pro (Late 2013) unit. - -

I was still using a more complete featured TVPaint application on my early 21st century PowerPC “Amiga” . . . until that machine ceased working.
So, post-Amiga I moved on to S/H Macs . . . from Minis, 24” iMac, to PowerMac 4.1, and my current mid-range PowerMac 6.1 with 32GB RAM.
With the later Macs (and their 2GB / 3GB graphics allied with dual QHD 2560 x 1440 curved displays, I often begin work with a background image LARGER than 2560 x 1440 pixels . . . SEASHORE being my major tool for final production.

As LEFT - RIGHT - TOP or BOTTOM (Usually TOP) extremities of the image become superfluous to my final image (usually only 1440 pixels high), I’ve used the previous IMAGE Tool to “crop” the image of unwanted picture features (areas) . . . yet still sometimes using a gross image reduction to achieve my final 1440 height sought. I have no need of larger images, and some-times work right down to individual pixels on the image (Magnifier Tool ! Indeed)

WITH the current very limited only Height and Width parameters available to me, I’m having to INVERT the image to CROP off Top Image pixel areas, and having to muck about with ‘Dragging’ the restored image back to the required 1440 “frame” as it usually “drifts” outside the required “position” during the LATER re-Inversion procedure! 

ALL THESE are so labor consuming (compared to just FIVE - SEVEN days ago) procedures that I may just have to resort to SAVING an Image, and IMPORT it to the GIMP - solely to employ GIMP’s CANVAS Sizing Tools . . . . as this is where SEASHORE presently fails me !!!!!!!!!!!!!!!!!!!!

Additional GRIPE . . . the current TEXT TOOL also gives me major problems. Formerly it was very easy to “fit” a block of text inside a WORD Balloon or a THOUGHT Balloon. PRESENTLY, it takes multiple drags of successive dotted-boxes to FIT each line of TEXT inside the WORD (or THOUGHT) Balloon limits . . . often times with recourse to UNDOs at more than one time.

The previous TEXT TOOL was magic . . . the present one is quite TRAGIC !!!!!!!!!!!!!!!!!!!!!

I had been using SEASHORE (up to now) for likely more than 14 years.  It was quite a let-down to make a financial contribution 
(no problem with that; a Workman deserves his Wages) 
only to be left with a less-helpful application than what I was using just 7 days prior!


Regards
John Klumpp
PLAINLAND QLD AU

1983 - C64
!988 - A500 Amiga
1990 - A2000HD, eventually with 68060 / 50MHz, 64Mb, Picasso II+, dual SCSI Adaptors and up to six SCSI HDDs + VIDI 24RT Frame Grabber & HP ScanJet A4 Scanner.
2003 - Amiga G4 SE with AmigaOS 4.1
Since, a series of S/H Macs, up to Power Mac 4.1 & Power Mac 6.1 (both 32GB Ram)

**Comment by robaho** [comment]
Hi John,

I am sorry these changes have caused you troubles. Can you please file a separate issue for the text tool with the details - from my understanding the new tool should be much easier for your use case.

As to the image positioning issue...

I can see for your case how this change would affect you, but I think the work around is the same number of steps. The reason that the positioning options were removed is that they are somewhat duplicative and the multiple ways of accomplishing the same function were confusing users. As I am sure you realize, the canvas is just a window through which the layers are visible. So, you can reposition the canvas (old version), or reposition the layers in the window.

Simply link all of the layers (if you have multiple), and then reposition the key layer using the offsets in the layer properties - where you can still use numeric input rather than having to drag - and the other layers will follow. You can also use the keyboard for fine positioning with the position tool.

Also, if you decide to drag the key layer - the 'delta values' in the 'point information' will show the values making it much easier to drag into position.

update: when verifying the above, I realized that changing the layer offsets for a linked layer does not adjust the linked layers... bummer - I will file a bug. So the only option is to drag the linked layers.

Finally, I will look into bringing back the canvas positioning. I think it was the combination of sizing and positioning that may have been confusing - possibly simply just the wording.

**Comment by robaho** [comment]
Another issue with the dialog to change the canvas position, is that you can't see if the adjustment - so it can cause a lot of trial and error. Using the position tool and linked layers makes it easy to see what the final canvas/image will be.

**Comment by robaho** [comment]
OK, I think the simplest solution is to use the crop tool, and set a custom aspect ratio to the desired size, then use 'crop image'. There is a bug, but in a future release it will retain these settings - so it will be easy to make similar changes to multiple images.

**Comment by vortexau-jk** [comment]
Ah Robert,

Is there an easy way to revert to the previous version of SEASHORE?  Up until the message calling for User financial conmitment appeared at the Top- that earlier version of SEASHORE was pleasing to my use. Certainly, with SEASHORE’s ability to IMPORT overlay images with transparent backgrounds in Layers, and arrange those Layers at the User’s call- I did find the earlier SEASHORE version to be an important Tool for final image assembly.

The major reason why I would reduce the TOP Boundary of an image that I would be working on, is to remove unwanted Sky from an image assembled on a City / Beach / Parkland image (Anime background/s that I store in several directories often have TOO Much unwanted sky after they are scaled-up to overlap my QHD display.)

Admittedly, I do use other Paint applications (sometimes even "the GIMP”) to prepare image elements ready for my final finish, and assembly, in SEASHORE.

Mind you, 27 years ago, and as late as 17 years ago even, I was using versions of TVPaint which had Tools for distorting overlay elements in the X, Y, and Z axis - like the flying transitions that the Video Toaster, used with NTSC analog television, could perform as an animation. Additionally, there was rub-through capacity where the User could Erase a “window” on the Top-most Layer to blend-in a feature on an underlying layer. The Non-Junior version of TVPaint (as compared with the cut-down version supplied with Picasso II+ 24bit colour boards) had features which I have never discovered since! 

The late 90s (1995 - year 2000) were somewhat of a golden era for the declining numbers of Amiga users, as UK magazines bought-up superseded Amiga applications in magazine-licensed usage numbers made available to consumers for the price of the magazine with cover-mounted CD-Rom.
Thus, I could upgrade versions of Personal Paint Copyright 1992-1995 (from Cloanto, Italy) who were one of the FIRST Users of the PNG image format, and TVPaint itself.

Regards
JOHN KLUMPP
Plainland QLD AU

**Comment by robaho** [comment]
Also, if you are unhappy that you made a financial contribution to the project - please private message me your receipt from Apple and I will issue a refund. (I think you may also be able to request a refund directly).

I am sorry if the changes caused you trouble. Version 3.0 is the result of a lot of hard-work and attempts to make Seashore the best easy to use image editor available.

**Comment by robaho** [comment]
In version 3.1 I have added the top/left offsets which is a bit easier to understand for users - so change the canvas size and position.

A future version will add a preview image so you can get a general idea of the pending change.

I still think it is easier to use the crop tool with a custom aspect ratio - especially in 3.1 - because the 'point information' correctly show the upper left corner of the crop rect.
