### ISSUE TITLE
Gray 3D border

### ISSUE THREAD

**Issue by mugsuk** [robaho/seashore#167]
Hi Robert

More of a request than an issue: is it possible to remove the gray border to the right and bottom of the image being worked on as I find it distracting (see attached screenshot)

Thanks for keeping the project alive - my favourite MacOS app!

Murray
<img width="1594" alt="Screenshot 2022-08-20 at 10 50 04" src="https://user-images.githubusercontent.com/38717962/185723338-9c467ee7-a981-4bee-956a-ccbd29fa5577.png">

**Comment by robaho** [comment]
I will add a preference option in version 3.8. Thanks for supporting the project!

**Comment by robaho** [comment]
fixed in 3.7

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/4958833/185726590-2985f489-09cc-4ddd-999b-56b6ee462adf.png">

**Comment by robaho** [comment]
fixed in 3.7

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4958833/185726609-4c943a6a-2b59-4703-8c69-82e675513a3b.png">
