### ISSUE TITLE
trivial operations doesnt work

### ISSUE THREAD

**Issue by yik77** [robaho/seashore#169]
i have (hesitantly) updated to Version 3.9.2 (2022101301) from some old and ancient one. Now i can not even select with drag and drop or crop bitmap. please advise. i have 10.13.6 (17G14042) OS X.

**Comment by robaho** [comment]
Does the program crash? Can you use screen capture to attach a video? I really don’t know what you mean.

**Comment by robaho** [comment]
Closing due to no response.
