### ISSUE TITLE
disk image couldn't be opened

### ISSUE THREAD

**Issue by pook52mb** [robaho/seashore#17]

**Comment by pook52mb** [comment]
https://github.com/robaho/seashore/releases/download/v0.6.6/seashore-bin-0.6.6.dmg
https://github.com/robaho/seashore/releases/download/v1.1.3/seashore-bin-1.1.3.dmg

Will not open on 10.9.5.  Reason: no mountable file systems.  APFS???

**Comment by robaho** [comment]
changed to HFS+ in 1.1.4 so you should be able to open it now
