### ISSUE TITLE
Can you make it work better on El Capitan

### ISSUE THREAD

**Issue by Squid4572** [robaho/seashore#175]
Dear Seashore team,
I understand El Capitan kinda old, but it would be really useful to be able to run Seashore on it. I can open the app but everything looks wrong and half the tools do nothing but draw grey boxes over my screen that disappear when I scroll. Thank you for your time!

**Comment by robaho** [comment]
The 3.11 version should fix this - it should be available rather soon. I have reworked a lot of the code and am testing as far back at 10.9. I will install a El Captain VM and test there as well.

**Comment by robaho** [comment]
I was unable to install a VM running El Capitan - but I did verify all functions in version 3.11 on OSX 10.9 (Mavericks) and it is now working great - so I don't expect you'll have any problems. If you do, please re-open this issue and add screenshots/videos of the problems you are seeing and I will see what I can do.

**Comment by robaho** [comment]
3.11 has been released. Please let me know if it solved your issues. I was unable to install El Capitan due to its age and expired certificate checks.

**Comment by Squid4572** [comment]
@robaho 

https://user-images.githubusercontent.com/80015221/206796191-23b327e3-fd69-4603-94da-d98b5dcaa0cd.mov

Sorry about low quality video, Github said it had to be under 10 megabytes.

**Comment by robaho** [comment]
Did you try the latest release in the App Store? Version 3.11 should work on El Capitan - it works on Mavericks.

Is this by chance a Hackintosh and not a real Mac ?

**Comment by Squid4572** [comment]
This is on a real Mac, I do not use Hackintoshes and I'm against the concept in general. I just checked the about section in the app and it says that it's 3.10, but interestingly the App Store doesn't show an update button, I am going to try uninstalling and reinstalling, hopefully that will work, I will add another comment when I am done.

**Comment by Squid4572** [comment]
I got it to update but it is still seems quite buggy I will try to upload a video here tomorrow.

**Comment by robaho** [comment]
Also, please make sure it’s 3.12 - not 3.11. 3.11 was bad.

**Comment by Squid4572** [comment]
After deleting and reinstalling I got 3.12.

**Comment by robaho** [comment]
Is 3.12 working as expected?
