### ISSUE TITLE
Keystone Correction Tool

### ISSUE THREAD

**Issue by dadr** [robaho/seashore#176]
Enhancement Suggestion:  I could really use a keystone correction tool.   Most of the parts seem to already be developed.  The polygon lasso tool is good to select the keystone, and the perspective transform tool does almost the right thing.   The problem with the existing perspective transform is that you have to guess at the points to correct the keystone, and then typically stretch back the result.   Is it the case that a proper transform for the perspective tool is a two-axis flip of the points of a keystone picture?  It just feels really close to having the function I need.   The reason I need it is that my wife makes copies of her siblings photos, but doesn't bother to try to align the phone to square up the picture.  Like the following...

![IMG_4323](https://user-images.githubusercontent.com/6684314/206234209-c2a95143-a378-42a3-95e1-c0e0926d96e5.jpg)

Thanks and Best Regards!

**Comment by robaho** [comment]
I have a solution for this in 3.12. Can you attach a raw image and a corrected one to ensure it works as expected. You should be able to PM them to be if need be.

**Comment by dadr** [comment]
Hi @robaho,
That's great news!   I've attached a before and after here.  Let me know if I can help in any other way.   
![IMG_5145](https://user-images.githubusercontent.com/6684314/206878022-2c0377e1-209f-4a0b-b34f-aaeca35902f4.jpg)
![IMG_5145 jpg](https://user-images.githubusercontent.com/6684314/206878028-d92cb6b4-75f3-4f9a-94cb-3064333c79fc.jpeg)

**Comment by robaho** [comment]
If you update to the latest 3.12, you have the keystone correction filters under Geometry.

**Comment by dadr** [comment]
I tried the App Store, but it did not show an update was available.  I’m on 3.11.  Is there another source?

**Comment by robaho** [comment]
You may have to search/refresh. My testing shows it is available now. Maybe based on location it may not be available yet.

**Comment by robaho** [comment]
You should be able to drag the points (the X's) after the selection. You need to 'Apply' the effect before switching to another tool - otherwise it automatically 'resets'.

Is it possible to attach a video of what you are trying?

**Comment by dadr** [comment]
NP see attached.  Let me know if you'd like to see a different "workflow." I had to reduce quality to get it to upload here.  If it's too blurry I can upload to google drive and share a link.

https://user-images.githubusercontent.com/6684314/207102557-8ae4457c-ab96-49fe-b2ac-d67e04bf3433.mov

**Comment by robaho** [comment]
I think you simply need to drag the 'X' after placing the 4 of them to adjust the skew. It doesn't do it automatically. (I am looking at a way to do that).

**Comment by robaho** [comment]
The keystone and perspective correction plugins required OSX 10.15+ - that is why they are not working. I am looking at reporting this more clearly in a future release. Sorry.

**Comment by dadr** [comment]
Oh!  That's sad. But let me thank you for all the time and effort you put into my problem  Many Thanks!

**Comment by dadr** [comment]
I just tried it in 3.16.  The behavior has changed, now I see the three options for keystone, but when I try to use one, I get the attached message and then the option is greyed-out afterwards. (I'm on OSX 10.14.6)
![Screen Shot 2022-12-23 at 11 26 25 AM](https://user-images.githubusercontent.com/6684314/209367643-9a2d5d81-7b1d-4d63-af52-4291b26bb834.png)

**Comment by robaho** [comment]
The keystone filters are not available in your version of OSX, BUT the "perspective correction" should be - and that is what you should use anyway. It is easier and works well - I tried it on the sample image you submitted.

**Comment by dadr** [comment]
Yes, I can confirm that perspective correction works on my computer.   I will give it a try.  It works on the example of photos where the “box” is at the outside edge of the image.   It doesn’t work so well when the rectangle is an interior feature of the image.  ( Or I might just need to learn something clever about the crop slider on that tool !)

**Comment by robaho** [comment]
Try using the “detect rectangle” and see where it placed the points. Then you can manually adjust the points.
