### ISSUE TITLE
newest update keeps crashing, won't let me move layers

### ISSUE THREAD

**Issue by angelsaves** [robaho/seashore#178]
seashore updated today. i spent a good hour trying to arrange 3 images in their own layers on the background - they kept snapping back to previous positions, and then the app crashed. several times it crashed immediately after opening, as well. help :(

**Comment by robaho** [comment]
I am so sorry about that. What version of OSX are you running? Did you report the crash via 'apple crash reporting'?

There should be a crash report on the disk - you can use the Console app to see the crashes, and then please attach it here.

**Comment by angelsaves** [comment]
i'm running ventura 13.0, and yes, i did report the crash - i attached it (i think). oh! i'll try that next time.
[crash.txt](https://github.com/robaho/seashore/files/10198766/crash.txt)

**Comment by robaho** [comment]
OK. Thanks. I am working on it. I should have it fixed tonight - hopefully the App Store will release it by tomorrow.

**Comment by robaho** [comment]
Also, please let me know of the 'apply transform' fixes the 'snapping back' issue.

**Comment by angelsaves** [comment]
oh, blessings on you, your household, AND your cow! i must have unticked 'auto apply transform' somehow - i'm going to blame the cat, probably.

**Comment by robaho** [comment]
There is a crash though when moving layers. I have it fixed and I will be posting version 3.12 tonight.

**Comment by angelsaves** [comment]
awesome! this is the fastest response i think i've ever gotten in my life. a++ experience, will continue to recommend to everybody i know
