### ISSUE TITLE
What happened to Seashore?

### ISSUE THREAD

**Issue by JacobLActon** [robaho/seashore#179]
Seems suddenly I cant move photos around anymore  - when I put it where I want it on the background, and import a new photo layer they all reset back to the middle.  Then the system crashes.  Been using Seashore daily for over 10 years.  Seems its unusable after this last update.

**Comment by robaho** [comment]
Please make sure you have 3.12. You need to apply the transform or turn on the auto apply.

**Comment by robaho** [comment]
closing as this was resolved in 3.12.
