### ISSUE TITLE
Auto Enhance died

### ISSUE THREAD

**Issue by Gewurztraminer** [robaho/seashore#181]
There was an error and Seashore disabled Auto Enhance.
The response suggested the OS is too old, but it's an M1 running Ventura.

![Screenshot 2022-12-19 at 21 38 58](https://user-images.githubusercontent.com/5916105/208569138-6f70eb23-4357-4cdc-b5bf-700f3affa695.png)

**Comment by robaho** [comment]
Sorry about that. I will look into it. Thanks for filing the bug.

**Comment by robaho** [comment]
Can you check the console app for a related message and post the detailed error/stack trace here?

**Comment by robaho** [comment]
This is fixed in 3.15 which should be available in the App Store shortly.
