### ISSUE TITLE
Seashore main window doesn't cast any shadow

### ISSUE THREAD

**Issue by Draykan** [robaho/seashore#182]
It seems that the main Seashore window is not casting any shadow on the background.
Additionally, it seems it's missing the thin (1 pixel width?) standard border, too.
The About and Preferences windows are fine, though.

![image](https://user-images.githubusercontent.com/151580/209486437-72e1f07a-0ccc-4aa9-9ca0-62cad371ac53.png)

SeaShore 3.16 (2022122201)
macOS Monterey 12.6.2 (21G320)

**Comment by robaho** [comment]
Fixed in 3.17. Looks like a bug in OSX - that when you remove the shadow, it also removes the border. Anyway, I figured out another way to solve the original issue.
