### ISSUE TITLE
Brush is currently non-functional

### ISSUE THREAD

**Issue by MagnetarRocket** [robaho/seashore#184]
Downloaded seashore from mac app store and currently so far, brush is completely non-functional.

**Comment by robaho** [comment]
Hi. I’m sorry you’re having problems. I just tested and it seems to be working fine. Are you running the latest 3.19 version? There was a bug in earlier versions of the spacing and brush was small.

**Comment by MagnetarRocket** [comment]
A update from the app store fixed it, closing now.

**Comment by robaho** [comment]
Great! Sorry about that
