### ISSUE TITLE
Seashore V3.20 OS MOJAVE

### ISSUE THREAD

**Issue by Dream-Rider** [robaho/seashore#185]
Hi,
I wondered why Seahore regularly shows up as having the same, repeated update on my Mac running Mojave?
Seems to be stuck in a loop.
Regards

Phil

**Comment by robaho** [comment]
I don’t think it is the same repeated update. I have been releasing many updates recently to fix reported crashes.  I have it set to not show the “what’s new” unless it is something major. 

I expect 3.20 to be the last update for a while (unless I get crash reports ;)
