### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by thoran** [robaho/seashore#186]
Consider the options provided by iina for sponsoring their project. See: https://github.com/iina/iina... These allow for regular payments. I would be prepared to sponsor per month a smaller amount, but over a year it would be more!

**Comment by robaho** [comment]
That is an interesting thought. Thank you for referring it to me - I was not aware of that program. I will have to do more research.

My gut feels that a subscription/sponsorship may be too much.

At the same time, it is my understanding that many universities recommend/use Seashore as a tool for their students - and so they may be in the position to better support the project.
