### ISSUE TITLE
Consider updating buildnotes.txt

### ISSUE THREAD

**Issue by thoran** [robaho/seashore#188]
The incantations out of the box here, https://github.com/robaho/seashore/blob/master/buildnotes.txt, don't work on Ventura at least...

1. With building for the App Store, I need a signing certificate.
2. With building a .dmg, I needed to specify `MACOSX_DEPLOYMENT_TARGET = 13.0` instead of `MACOSX_DEPLOYMENT_TARGET = 10.9` in `Seashore.xconfig`, but then I need a signing certificate again.

While I can find an old certificate or create one, I thought it might be good for the build instructions to be more comprehensive maybe.

My specific purpose was to make a Homebrew recipe which downloads the latest zip file and compiles the app, since there isn't a Homebrew recipe as yet, since that is preferred over using the App Store for installation.

**Comment by robaho** [comment]
There are earlier issues regarding Homebrew that you can review. For a variety of reasons it is not on the top of my list of priorities. It was previously available there - I had provided DMG releases - but it amounted to less than .1 % of all Seashore users. It simply wasn't worth the effort.


That being said, Seashore certainly builds and runs for 10.9 (as the minimum release). I verify this when testing new releases.

**Comment by thoran** [comment]
From https://github.com/mas-cli/mas...
```
$ brew install mas
($mas search Seashore) # Find the App Store ID.
$ mas install 1448648921 # Install Seashore to /Applications.
```

**Comment by robaho** [comment]
From that page…

> Over time, Apple has changed the APIs used by mas to manage App Store apps, limiting its capabilities. Please sign in or purchase apps using the App Store app instead.

**Comment by thoran** [comment]
It was still working when I tried it for Seashore a few days ago at least. I thought I would document the alternative here for others who may stumble upon it when looking for a similar solution.

**Comment by robaho** [comment]
Like so said, please review the earlier issues. Brew has some significant downsides for developers. For many projects it’s very helpful - for others not do much.

**Comment by thoran** [comment]
I'm not aware of those downsides. Perhaps you could deal with such questions pre-emptively by addressing that in documentation somewhere if you feel the need to do so.

**Comment by robaho** [comment]
Thank you for the feedback.
