### ISSUE TITLE
Resizing image causes wavy lines

### ISSUE THREAD

**Issue by fovlet** [robaho/seashore#193]
I've been using Seashore for years, mostly to reduce and touch up pictures of dollhouses under construction before posting them on my blog. Recently I've noticed an issue with straight diagonal lines becoming wavy when the image is reduced. I don't remember this being a problem before, so I think it started when I updated to version 3.21.

Here's an example:

The original image: https://emilymorganti.com/dollhouse/mansard/IMG_3574.jpg (this is a dollhouse turned upside down -- the white textured area is ceiling paper)

Cropped and resized in Seashore: https://emilymorganti.com/dollhouse/mansard/mansard200.jpg (the edge of the ceiling paper and the gray edge beneath it look jagged)

Cropped and resized in Photoshop: https://emilymorganti.com/dollhouse/mansard/mansard200a.jpg (the edge of the ceiling paper and gray edge are smooth)

I tried each of the interpolation options in Seashore's Scale Image dialog box and had the same result. I'm not sure if there are other settings I should be trying, or if this is a bug?

**Comment by robaho** [comment]
Can you attach the scaled images - not a screen capture of the scaled images?

**Comment by fovlet** [comment]
Sure - 200 is resized in Seashore 3.21. 200a is resized in Photoshop.

After posting my question, I downgraded to Seashore 2.5.10 and tried it, and the line is smooth. I've attached this too (200b).

Let me know if I can tell you anything else that would help.

![mansard200](https://user-images.githubusercontent.com/74070841/232368072-0f12f594-2761-487a-a67b-4b743ced7972.jpg)
![mansard200a](https://user-images.githubusercontent.com/74070841/232368078-fd4e3d52-ef87-4960-916a-d5fd1c202db5.jpg)
![mansard200b](https://user-images.githubusercontent.com/74070841/232368081-46927d66-83e4-42d3-ad53-ab5235fe2b90.jpg)

**Comment by robaho** [comment]
Can you attach the original before the resize so I can replicate?

**Comment by fovlet** [comment]
![IMG_3574](https://user-images.githubusercontent.com/74070841/233171266-1f28307b-ede4-4945-a2aa-81c8ca188973.JPG)

**Comment by robaho** [comment]
fixed in 3.22

**Comment by robaho** [comment]
I changed SeaShore to always use high-quality scaling. I may add back in the ability to change the interpolation quality in the future - most likely with a quick toggle.

**Comment by fovlet** [comment]
Thank you!
