### ISSUE TITLE
Magic Wand

### ISSUE THREAD

**Issue by mugsuk** [robaho/seashore#195]
Enhancement Request

Hi Rob. Any chance of implementing Instant Alpha, or the Magic Wand Select as used in preview and Acorn? This would be incredibly useful.

Thanks for an excellent piece of software.

Thanks

Murray

**Comment by robaho** [comment]
Can you describe how it works in a bit more detail?

**Comment by robaho** [comment]
Never mind, I checked out Preview. I can see how the live selection change would be helpful with the drag (you can drag with the wand in Seashore - but it doesn't preview live).

Thanks for the idea.

**Comment by robaho** [comment]
This is available in version 3.26 which should be posted to the app store this evening. You can drag left and right with the wand and the bucket tool to adjust the tolerance.

Thanks for the great idea.

**Comment by mugsuk** [comment]
Thank you so much Robert

It was the only thing I ever missed when using your amazing App previously.

**Comment by robaho** [comment]
Thanks. I am not sure I am happy with the performance of adjusting the tolerance vs the old behavior of adding more color matches. I may make it an option. Either way, I will keep the preview which I think is the important aspect.
