### ISSUE TITLE
No buttons to add text as a layer or merge with layer

### ISSUE THREAD

**Issue by ebow77** [robaho/seashore#196]
<img width="1512" alt="Screenshot 2023-05-12 at 18 10 42" src="https://github.com/robaho/seashore/assets/95896618/84048a2d-a12e-42e7-9574-0e9ec2a1a452">

I don't see any buttons that allow me to "set" the text. In a video you posted for another issue, it shows two buttons, something like "add as layer" and "merge with layer" (the video is very small and I can't zoom it). For me, there are no buttons there, no matter how wide I make that right-edge panel. So the text tends to disappear unless I switch to some other tool, and even then it seems to disappear when I try to do other things. 

Can you please advise how to get these buttons to appear, or if it's a bug? 

I'm running Version 3.22 (2023042401) on macOS 13.3.1 (a), on an M1 MacBook Pro. 

edit: just updated to Version 3.23 (2023050501) and the problem remains.

**Comment by robaho** [comment]
Hi. I think the video you are referencing is old. That is before Seashore supported actual "text layers" (it only supported text as an image prior).

Please watch this video to see if it makes more sense: https://www.youtube.com/watch?v=7HxvU0H8urc

You don't need to "set" anything anymore. The text is always a layer. If you want to convert it into a bitmap, you can merge into a bit map layer.

In the screenshot you attached to this issue the text layer looks fine. What exactly are you trying to do?

Feel free to reply back with any questions.

**Comment by robaho** [comment]
I do see one issue. In your light mode, the buttons just above the text to set bold, italic, etc. are not visible. I think they are white on white. I am going to test and try and correct that this evening.

**Comment by robaho** [comment]
all of these issues should be fixed in 3.24 which I am posting now - should be available tomorrow.

**Comment by ebow77** [comment]
Thank you, works great now!
