### ISSUE TITLE
bucket not working properly in 3.26

### ISSUE THREAD

**Issue by luey33** [robaho/seashore#197]
New user.
In a new image, I copy your steps in the video exactly in version 3.26 and the bucket doesn't work properly. I downloaded version 2.5.10 and it works fine. I think I'm following the same steps exactly. I believe this is a bug.

**Comment by robaho** [comment]
Do you click and drag? What is the tolerance set to? Did you check the color?

**Comment by luey33** [comment]
Hi Robert,
OS is 11.7.4
I have tried different tolerances. It is a new image and a basic shape from the toolbox - exactly like the video on YT.
I have tried clicking, dragging but it either doesn't work, or the entire image changes color.
In the 2.5.10 version, it works perfectly for me.

**Comment by robaho** [comment]
Have you tried dragging a bit and holding there for a moment/while? It could be that slower computers cannot redraw fast enough. Please try and let me know. I am looking at doing another release tonight so it would be great to figure out what is happening.

**Comment by robaho** [comment]
I think I see the bug. You have to click and drag a bit - simply clicking on the image won't work. I am working on a fix.

**Comment by robaho** [comment]
Yea - that is another bug. The bucket fill does not respect the selection. I am working on it but it won’t be fixed until tomorrow.

**Comment by robaho** [comment]
This is fixed in 3.27 which has been posted to the app store this evening. Sorry for the inconvenience.
