### ISSUE TITLE
pasting formatted text in text tool shows very small

### ISSUE THREAD

**Issue by luey33** [robaho/seashore#198]
When I type into the text tool, all is good. 
But if I copy text from somewhere like gmail where it might be formatted, the text shows up in the tool as too small to see. I believe the tool should strip formatting.
Not a huge bug but might be something to address. See screenshot attached.
<img width="273" alt="Screen Shot 2023-05-31 at 10 44 31 AM" src="https://github.com/robaho/seashore/assets/134538771/c32fcf73-779d-40da-8650-0a383e3c2f2d">

**Comment by robaho** [comment]
This is fixed in version 3.29 which has been posted to the AppStore and should be available in the next 24 hours.
