### ISSUE TITLE
Quitting when I want to fill in any objects

### ISSUE THREAD

**Issue by ardakaykusuz** [robaho/seashore#199]
When I want to fill in the objects that I drew, the application is quitting and brings an error code. It occasionally works fine as always. By the way, it started to occur after the last updates.

**Comment by robaho** [comment]
I’m so sorry. I’ve noticed a few people having crashes with that operation and have been trying to replicate so I can fix but I’ve been unable to. I will try again this evening to see if I can figure out what is going wrong.

**Comment by ardakaykusuz** [comment]
Thank you so much for your interest!!

**Comment by robaho** [comment]
This is fixed in 3.30 which will be posted to the App Store tonight. The crash happens if you start the wand or bucket outside the boundaries of the current layer. Both of those tools only work on the current layer.
