### ISSUE TITLE
Turn off Layers

### ISSUE THREAD

**Issue by radicalsingularity** [robaho/seashore#200]
How do I turn off layers in seashore?  I am constantly having to flatten my image.

Also, I would rather have the background color be just another foreground color so that I could right click it if I wanted that color instead of the main one.  Is there any way to alter it so that it is a foreground color?

**Comment by robaho** [comment]
I am not sure what you ask asking for here. If you do not want layers do not add layers. The only time this is required is if using the text tool, but you can flatten all of the once at the end.

Also, if you save an import that does not support layers Seashore automatically flattens the image - there is no need to do this manually.

I also do not understand your ask about the colors. Seashore has a foreground color and a background color. The background color is used for "erasing" when there is no transparency. You can use the swap colors command or icon to swap the foreground and the background. You can use the 'recents' panel to quickly change between different tools and color sets.

@radicalsingularity can you describe a bit more about your issues? If I don't hear from you I will assume the above helped and I will close the issue.

**Comment by radicalsingularity** [comment]
I don't know what I am doing.  So, my descriptions are from a neophyte.  However, here is what I do.  I take either the pencil or the square selection tool or the paint bucket and then I do something.  Before I can do something else, I have to go flatten the image.  Then I can draw again.  I am not an artist so maybe I mean background which I also do not need.  I just want a simple canvas that I can draw on.  No fancy stuff.  Currently, I am using it to make a map of my world for my novel.  So, I draw places on my black and white map and cut and paste stuff.  I copy stuff open an new map and paste from copy onto it so I can rotate it and then copy it and then paste it back into the original.

What I need is no layers, no background.  Just a simple canvas upon which I can draw.  I am sure that your seashore is too powerful but it is all I have.  If there was a way to just have a simple single canvas with nothing fancy no doodads no frills.  Just a square, round. or lasso selection tool & a pencil & a paint bucket.  That would be great.

I don't remember what the color thing was about unless it was in reference to the two colors and the right click being the second color.

Anyway, I use seashore and struggle.  If you have any advice that would be great.  or if you could add a way to open/start/begin a simple no frills canvas that would be best.

Also, I don't know why that when I draw there are lesser shades of black.  So that it is black and then next to it lesser black then almost white then white.  The same thing happens when I use text.  I just want black text.  So, I don't know what I am doing wrong there.  Anyway,

Thank you for the help.



________________________________
