### ISSUE TITLE
problem dragging crop selection area

### ISSUE THREAD

**Issue by marisademeglio** [robaho/seashore#202]
As shown below, it's not really possible to move a selection area when using the crop tool, because even if I just try to move it a little, it flies off the screen. 

This doesn't happen for selections made while not in "crop" mode.

I'm using 
* Seashore version 3.31 (2023062901)
* macOS version 13.4.1 (c) (22F770820d)
* 2018 mac book pro (intel)

I tried it with the setting for "mouse coalescing" both on and off but it didn't make a difference.

https://github.com/robaho/seashore/assets/734730/0eb88559-24f0-4f24-ba75-a51c49e586d2

**Comment by robaho** [comment]
This is fixed in 3.32 which will be posted to the App Store this evening. Thanks for reporting the issue.
