### ISSUE TITLE
Modify right mouse button to draw bg color instead of erasing

### ISSUE THREAD

**Issue by radicalsingularity** [robaho/seashore#203]
How do I modify right click so that pencil  is the opposite color.  Example.  In the upper right hand corner it shows to colors.  When I right click the eraser comes up.  I would prefer that the opposite color is selected instead.  Currently, I have to go and flip the colors manually so that I get the other color.  Example.  When using pencil, left click makes black, if I right click it brings up the eraser.  I would want the other color, in this case white, to be what occurs when i right click.

Is there a way to modify right click so that it chooses the other color instead of earase?

Thank you

**Comment by robaho** [comment]
If the layer does not have transparency the right click will draw with the background color instead of erase. Otherwise I would need to add a setting.

**Comment by robaho** [comment]
This is addressed in version 3.33. I added a preference to making drawing with the right mouse button always use the background color.

**Comment by radicalsingularity** [comment]
> This is addressed in version 3.33. I added a preference to making drawing with the right mouse button always use the background color.

How do I do that?

**Comment by radicalsingularity** [comment]
Personally, I would prefer to turn off layers.  I am not an artist and I do simple drawings.  I find myself always having to go up to the tool bar and merge layers after I make changes.  I would like to never have layers.  Is that possible?

**Comment by radicalsingularity** [comment]
Hello, I would like to know how to turn of layers.  I would also like to know how to turn off transparency.  I read your post on the forum.   I am not tech savvy so if it is complicated, I would need help with that.  Thank you,
________________________________

**Comment by radicalsingularity** [comment]
I am running 3.9.2 but I do not see where to click the preference.
________________________________

**Comment by robaho** [comment]
You need to update to version 3.33 to have the preference. When you create a new image you can control transparency using the checkbox. You can also hit the info button on the layer to turn off the alpha channel (transparency). 

There is no way to turn off layers. I can see about adding something like that but it’s a big change and it will lose a lot of functionality. 

You may find a simple paint program more suited to your needs. They usually don’t have layers.

**Comment by radicalsingularity** [comment]
I tried starting a new...  and the transparency was not checked.  Then I took my pencil and drew a squiggly line.  Then I took the square selection tool and selected it.  Then I hit control-X then I hit control V (paste).  But the only place I could draw was in that square box.  Until I merged layers.  So I am not doing something right.  Also, right click is still erase.
________________________________

**Comment by radicalsingularity** [comment]
Hi Mr. Engels, I just talked to my friend and he looked up seashore in the apple app store.  He said that there was a 3.33 version and that I should download it.  So I did.  It is wonderful.  I clicked it to edit only primary and then tranparency is off NOW when I right click the white works!!! YEEEEEHAAAA!!!!

My friend said that that color going from black to lighter black to lighter black to white is called anit alliesing or something like that.  It would be nice if I could turn that off.

Thank you so very much for being understanding of a simpleton like me.
________________________________

**Comment by robaho** [comment]
Based on email this is resolved.

**Comment by robaho** [comment]
There are different types of brushes. The ones without the soft edges will have a less effect. 

I think if you send me a screenshot of what you are referring to I might have an easier time helping.
