### ISSUE TITLE
Mac OS

### ISSUE THREAD

**Issue by dgerety** [robaho/seashore#205]
I've just replaced an Intel Mac from 2012 with a 2023 M2 Mac. I've had Seashore 3.33 for quite some time but have never needed to use it, until now. Seashore made the move to the new Mac and seems to want to work, but I don't want to put any time into it on this machine if it's not compatible. Should I stick with it on this computer or use the version on the old Intel Mac? 
Thank you, 
DG

**Comment by robaho** [comment]
I test and build for M1 macs. I haven’t seen any reports of issues. I don’t have an M2 to test on. 

Can you be more specific about what is not working?

**Comment by dgerety** [comment]
Thank you, Robert. I haven't gotten into it enough to know. My only concern is the intro post on Seashore that it is for Intel-based Macs. I thought I'd check that out before investing much time on it. Since you're running Seashore on an M1, I'm comfortable with it on my M2. Many thanks, David.
