### ISSUE TITLE
support for webm export

### ISSUE THREAD

**Issue by BirdInFire** [robaho/seashore#208]
Please can you add support for webm export.

Also decided to buy the support for helping you, good luck :)

**Comment by robaho** [comment]
Thank you for the support. I will look at adding webm this week.

**Comment by robaho** [comment]
Are you certain you don’t mean webp? Webm is a video format.

**Comment by BirdInFire** [comment]
> Are you certain you don’t mean webp? Webm is a video format.

yes webp my bad :)

**Comment by robaho** [comment]
This is fixed in 3.35
