### ISSUE TITLE
borders?

### ISSUE THREAD

**Issue by exdude11** [robaho/seashore#210]
Suddenly it seems that I cannot shrink an image as the black borders around it refuse to shrink below what appears to be 7 3/4 " by 6" regardless of the image being smaller than that. i need to view the image without any border, or at least much smaller. Something has changed.
<img width="421" alt="Screenshot 2024-05-28 at 5 28 54 PM" src="https://github.com/robaho/seashore/assets/171101084/041f1b85-b6f1-4941-af01-8a2adfd283c0">

**Comment by robaho** [comment]
Are you cropping the image in seashore? How are you trying to “shrink it”? If you could attach a video or at least a screenshot in seashore showing the options that would be helpful. 

Seashore doesn’t add borders. Are you sure it the viewer (Preview???) showing the image at a certain size?

**Comment by exdude11** [comment]
Can you see the image I sent? I have tried cropping, rectangle select, and entering size values manually. All that works fine . It is the black boarders that I’m trying to get rid of. It seems to me that I used to be able to shrink an image a bit smaller and the black border would shrink with it. It has always been there but much , much smaller than what you see in the image I sent. This is all within Seashore. If I save an image it’s saved with that black border. I cannot figure out how to get rid of that. If Seashore isn’t adding it I have no idea how or why it’s added. Does the app piggyback on Preview somehow in MacOS? I don’t see where that’s happening or how I could change a setting that would affect the view.

**Comment by robaho** [comment]
I can see the image you attached. If that is seashore that means you have removed all of the tool bars, etc.

I think if you use Preferences -> Colors -> Window Frame and you change the color to Pink, you will see that the "black borders" are just the blank space Seashore adds when viewing in order to center the image. If you save the image, that area is not saved with the image.

The video on cropping an image might help: https://www.youtube.com/watch?v=cV3ySjOms-k

**Comment by robaho** [comment]
Here is your image cropped, with the Window Frame color changed:

<img width="1079" alt="image" src="https://github.com/robaho/seashore/assets/4958833/7973f4c6-14f6-48ce-bb13-51bd158804a3">

**Comment by robaho** [comment]
If you zoom in/out you will see that the surrounding border (pink area) changes size in order to center the image.

**Comment by robaho** [comment]
Closing issue as there’s been no response. I assume the borders issue was as I described and not really an issue.
