### ISSUE TITLE
Resize lead the invisible border (who became white in some format)

### ISSUE THREAD

**Issue by BirdInFire** [robaho/seashore#211]
I actually use your tool to change very often size and format of a file, the problem is that I have so often the issue of a picture with a strange border who appear (witch become white in webp or jpg).

Here a picture (mine) from 1334px to 204px : 

<img src="https://github.com/robaho/seashore/assets/42673166/c17c2ca2-a2b7-4cdb-b17d-215ab8f36cc7" width="300px"></img>

This is quite annoying as this bug make the necessity of manual intervention to remove this empty zone witch take time.

**Comment by BirdInFire** [comment]
Ad additional information the original image where in PNG,
the version is : Version 3.35 (2024050201)
on Mac OS : 14.5
And I've taken the support (I don't expect the removal of the "support" message from the software being the culprit, but I prefer give you as much as information as possible).

there is the original picture of the one that cause the issue : https://wormhole.app/LJyWz#4KzsKiGAONdxPHNIQX0aXw (24h - 100 download Max)

**Comment by robaho** [comment]
This occurs when you scaled the layer to be smaller than the canvas size, and there is a background layer that is transparent.

If you use Image -> Scale Image you should not see this.

I cannot open the wormhole file as it says you left before finishing the upload.

<img width="930" alt="image" src="https://github.com/robaho/seashore/assets/4958833/dd1deec9-cc36-4ffc-9ec2-2a62724e5c56">

**Comment by BirdInFire** [comment]
1334x1334 -> 204x204
Here the full size

![IMG_6406](https://github.com/robaho/seashore/assets/42673166/d627cbde-738b-4f74-8162-64e2c4d33115)

**Comment by robaho** [comment]
Thanks. I was able to reproduce the issue. I think it is because the scaling ratios end up not being integral (e.g. 15.3) so you have a fraction of a pixel. I will look into it and see if I can add a fix.

Thanks again for reporting this.

**Comment by BirdInFire** [comment]
> Thanks. I was able to reproduce the issue. I think it is because the scaling ratios end up not being integral (e.g. 15.3) so you have a fraction of a pixel. I will look into it and see if I can add a fix.
> 
> Thanks again for reporting this.

No problem I also have a developer background I know the most difficult in a bug fix .. it's reproducing it :)

**Comment by robaho** [comment]
When I look at the layer, it says it is 205 x 205, even though the dialog had 204x204 so I am pretty certain it is a rounding issue. Should be an easy fix.

**Comment by robaho** [comment]
I was able to fix it. It is available in the 3.36 release which should be downloadable in 24 hrs.

**Comment by BirdInFire** [comment]
> I was able to fix it. It is available in the 3.36 release which should be downloadable in 24 hrs.

thanks :)
