### ISSUE TITLE
 the text doesn't work

### ISSUE THREAD

**Issue by gkrawchuk** [robaho/seashore#213]
I tried to add a new layer with the text and it just doesn't work. It's intermittent nine times out of 10 it just doesn't work when I try to put Text on a new image.

**Comment by robaho** [comment]
Are you certain the font size and color makes it visible? Did you watch the adding text video? There have been no other reports of a problem in this function 

can you attach a video?

**Comment by robaho** [comment]
Here is the video. https://m.youtube.com/watch?v=7HxvU0H8urc&t=150s

If it still doesn’t work for you feel free to reopen the issue.
