### ISSUE TITLE
Fill range issues

### ISSUE THREAD

**Issue by MinDeYuraDance** [robaho/seashore#215]
Hello.
I have a problem regarding the Fill tool.

It is not possible to fill an area where the color code is #00000, i.e., completely black.
The same is true even if the tolerance setting is set to 0.

![Figure1](https://github.com/user-attachments/assets/822e0114-f3fb-4099-91a0-6ad750d39210)
For other colors, the fill works correctly.
For example, a range of colors close to black, such as #212121, fills correctly.

![Figure2](https://github.com/user-attachments/assets/e0a141c2-5199-40aa-8e38-fbc4810aefa3)
If possible, I would like to fill in areas that are completely black as well.
Is this a specification?
I would appreciate it if you could confirm this.

*Environment
MacBook Pro 2023 (Apple M2 Max)
Sonoma 14.6.1
Seashore Ver. 3.37

*Translation tools are used.

================================================================
●原文 / Original text●

こんにちは。
塗りつぶしツールに関する問題です。

カラーコードが#00000、即ち完全な黒色である範囲を塗りつぶすことができません。
許容範囲設定を0にしても同様です。
(図1)

それ以外の色の場合、塗りつぶしが正常に動作します。
例えば#212121など、黒に近い色の範囲は正常に塗りつぶせます。
(図2)

可能なら、完全な黒色である箇所も正常に塗りつぶしたいのですが、
これは仕様でしょうか?
ご確認いただけますと幸いです。

【環境】
MacBook Pro 2023 (Apple M2 Maxシリコン)
Sonoma 14.6.1
Seashore バージョン：3.37

**Comment by robaho** [comment]
Thanks for reporting this. I will take a look today.

**Comment by robaho** [comment]
I tested this and it is working - except for a minor bug that is color independent. If you make the tolerance 1, it should work.

I am going to look into fixing it so that 0 means an exact match on the color of the selected point.

**Comment by robaho** [comment]
handling tolerance = 0 as an exact match is fixed in 3.38 which is being posted to the AppStore. I tested and I can fill black areas (although I could do this before with tolerance = 1)

**Comment by MinDeYuraDance** [comment]
Thank you so much for your prompt reply and response!
Actually, I have found two more problems and will post them separately.

I have been using this software for about 15 years.
I supported through app a moment ago.
I hope this helps a little.

Best regards.

*Translation tools are used.

======================================================
●原文 / Original text●

早急なご返信とご対応をいただき、本当にありがとうございます!
実はあともう2つ問題を見つけているため、別途投稿させていただきます。

かれこれ15年ほどこちらのソフトを愛用しています。
先ほど、微力ながらアプリから支援させていただきました。
少しでもお役に立てれば幸いです。

以上、よろしくお願い致します。

> 許容値 = 0 を完全一致として扱う問題は、AppStore に投稿されている 3.38 で修正されました。テストしたところ、黒い領域を塗りつぶすことができました (以前は許容値 = 1 でこれを行うことができました)
