### ISSUE TITLE
Linear tool Issue & Layer display/hide issue

### ISSUE THREAD

**Issue by MinDeYuraDance** [robaho/seashore#216]
1. Linear tool Issue

If I use the Linear tool with Shift key or Shift+Control keys,
The effect will continue even if I release those keys.
This issue can be removed by Undo or switching to another tool.

When Undo is used all lines drawn while the effect continues disappear,
so I think that everything is perceived as one stroke.

I attach a video:
https://github.com/user-attachments/assets/9054227c-6722-4ada-a67c-e22498d05ff4

If possible, I would like to return to normal drawing mode after releasing Shift or Shift+Control.

=============

2. Layer display/hide issue

By double-clicking the “eye” icon to show or hide a layer,
I can hide all layers except for that layer,
but this is applied even if I think you clicked slowly.

I think the reason is that the double-click interval is set wide in the application,
but if possible, I would like to add an option to turn off this feature... that is, just to show/hide only that layer when clicking in succession.

=============

In addition to these, I have several other feature requests (suggestions) that we will post at a later date.

I am sorry, but I would appreciate it if you could consider the above two issues.
I apologize for the length of this post.

*Environment
MacBook Pro 2023 (Apple M2 Max)
Sonoma 14.6.1
Seashore Ver. 3.37

*Translation tools are used.

================================================================
●原文 / Original text●

1. 直線ツールの問題

ShiftまたはShift+Controlを利用して直線ツールを使用すると、
それらのキーから手を離しても効果が継続してしまいます。
この現象はUndoをするか別のツールに切り替えることで解除されます。

Undoを使用すると、効果が継続している間に引かれた線が全て消えるため、
全てが1ストローク内であるように認識されていることが考えられます。

参考までに動画を添付いたします：(動画)

可能であれば、ShiftまたはShift+Controlを解除した後は
通常の描画モードに戻るようにしていただきたいです。

=============

2. レイヤー表示・非表示の問題

レイヤーの表示・非表示を切り替える「目」のアイコンをダブルクリックすると、
そのレイヤー以外を非表示にすることができますが、
ゆっくりクリックしたつもりでもこれが適用されてしまいます。

原因としては、アプリ内でダブルクリック間隔が広く設定されているためだと思いますが、
可能であればこの機能をオフにする…つまり、連続でクリックしても単にそのレイヤーのみの表示・非表示が切り替わるような…オプションを追加していただきたいです。

=============

これら以外にも、いくつか機能のリクエスト(ご提案)がありますので
また後日投稿させていただきます。

お手数をおかけし申し訳ございませんが、以上2点につきましてご検討いただけますと幸いです。
長文失礼致しました。

【環境】
MacBook Pro 2023 (Apple M2 Maxシリコン)
Sonoma 14.6.1
Seashore バージョン：3.37

**Comment by robaho** [comment]
Please only file a single issue per ticket. I am going to close this. Your first issue appears to be valid. The second, I tested, and I think you need to lower your double-click threshold in your system settings.

**Comment by robaho** [comment]
closed for multiple items in a single issue

**Comment by MinDeYuraDance** [comment]
I apologize and will do so next time.
Also, thank you for reviewing both issues.

For the first issue, I will re-submit.
For the second issue, I will make the change from the system settings.

*Translation tools are used.

================================================================
●原文 / Original text●
大変失礼致しました、次回からそのようにします。
また、どちらのissueもご確認いただきありがとうございました。

first issueについては再投稿させていただきます。
second issueについては、システム設定から変更するようにします。
