### ISSUE TITLE
Linear tool Issue (repost)

### ISSUE THREAD

**Issue by MinDeYuraDance** [robaho/seashore#217]
Sorry for the repost.

If I use the Linear tool with Shift key or Shift+Control keys,
The effect will continue even if I release those keys.
This issue can be removed by Undo or switching to another tool.

When Undo is used all lines drawn while the effect continues disappear,
so I think that everything is perceived as one stroke.

I attach a video:
https://github.com/user-attachments/assets/9054227c-6722-4ada-a67c-e22498d05ff4

If possible, I would like to return to normal drawing mode after releasing Shift or Shift+Control.

I would appreciate your confirmation.

*Environment
MacBook Pro 2023 (Apple M2 Max)
Sonoma 14.6.1
Seashore Ver. 3.37

*Translation tools are used.

================================================================
●原文 / Original text●

再投稿失礼致します。

ShiftまたはShift+Controlを利用して直線ツールを使用すると、
それらのキーから手を離しても効果が継続してしまいます。
この現象はUndoをするか別のツールに切り替えることで解除されます。

Undoを使用すると、効果が継続している間に引かれた線が全て消えるため、
全てが1ストローク内であるように認識されていることが考えられます。

参考までに動画を添付いたします：(動画)

可能であれば、ShiftまたはShift+Controlを解除した後は
通常の描画モードに戻るようにしていただきたいです。

ご確認いただけますと幸いです。

【環境】
MacBook Pro 2023 (Apple M2 Maxシリコン)
Sonoma 14.6.1
Seashore バージョン：3.37

**Comment by robaho** [comment]
This is fixed in version 3.39

**Comment by MinDeYuraDance** [comment]
Thank you so much for your prompt response!

Best regards.
