### ISSUE TITLE
Could not open with mac os high sierra 10.13.6

### ISSUE THREAD

**Issue by bacsojin1102** [robaho/seashore#26]
Version 2.1.5
I got compatible error when open the app.
Maybe this the same with issue #5 

![screen shot 2019-01-08 at 22 16 30](https://user-images.githubusercontent.com/11953561/50839547-20079980-1393-11e9-8048-1f8e332a25da.png)

**Comment by robaho** [comment]
@bacsojin1102 Hmm... I develop and test on High Sierra... Can you possible open the show details and paste here... just remove any personal information if need be. Thanks for your support.

**Comment by robaho** [comment]
@bacsojin1102 also, it may be the file that was last save/viewed and it is trying to open that... you might need to attach that file here as well if you can, but the show details might be sufficient

**Comment by robaho** [comment]
@bacsojin1102 one more thing, was it opening successfully with previous versions ? Thanks for your help. Just FYI, I can't really do anything on this until I get some answers to these questions because it is working for me.

**Comment by pfackelmann** [comment]
same here

Peter
[Seashore Process.pdf](https://github.com/robaho/seashore/files/2738151/Seashore.Process.pdf)

**Comment by robaho** [comment]
@pfackelmann do you by chance not have it installed in /Applications or possibly you use a custom user setup ?

**Comment by robaho** [comment]
Never mind, I see the problem. Working on a fix.

**Comment by robaho** [comment]
fixed in 2.1.6
