### ISSUE TITLE
Minimum OS since 2.1.4 is now 10.7

### ISSUE THREAD

**Issue by pook52mb** [robaho/seashore#28]
"The primary motivation was to allow Seashore to work on OSX 10.6+"

The last version to work with OS X 10.6 is 2.1.3.  Please leave it available on GitHub.

Also, please make changes to note that the minimum OS is now 10.7.

**Comment by robaho** [comment]
Trust me I’ve been trying to keep the version as low as possible, but in some cases you can’t make it work on modern os if you keep the old way. 

Still I will review and see if 10.6 can work. 

More importantly, I would be concerned about using 2.1.3. I would use an older version from sourceforge where all of the versions are. Probably go back to 0.6.6

**Comment by robaho** [comment]
@pook52mb Actually, I would not use any version past 1.1.5, but would also consider seriously using 0.6.6 instead as some of the early 1.x versions had "new bugs".

I did a review and 10.7 is going to be the minimum version. ARC requires 10.7 for weak references - the code is too hard to maintain without ARC, and there's no going back. Sorry. I am going to close this. I will update the documentation here to state hat 10.7+ is now required.

**Comment by pook52mb** [comment]
"If you are on an earlier OSX version, I suggest downloading the 0.6.6 binaries from seashore.sourceforge.net"

"changed to HFS+ in 1.1.4"

Would you please repackage https://sourceforge.net/projects/seashore/files/v0.6.6/seashore-bin-0.6.6.dmg as HFS+ for the few of us still using 10.6.

**Comment by robaho** [comment]
@pook52mb  I added an "hfs" dmg to the 0.6.6 folder.
