### ISSUE TITLE
Seashore crashes immediately on launch in OS X Mojave 

### ISSUE THREAD

**Issue by muesic** [robaho/seashore#39]
Just trying this app for the first time in years and it crashes every time I try to launch it. I'm running a mid-2015 MacBook Pro and OS X Mojave 10.14.4 (yea, I know that a beta of OS X, but it hasn't broken anything else that I know of).
Forgot to mention I was trying out version 2.3.0

**Comment by robaho** [comment]
@muesic Are you running the App Store version? If so you can report the crash log, if not, you need to post the crash log here so I can review.

**Comment by robaho** [comment]
fixed in 2.3.1

**Comment by muesic** [comment]
So what took you so long ;-) 

I also just now tried to download it from:
https://sourceforge.net/projects/seashore/files/latest/download <https://sourceforge.net/projects/seashore/files/latest/download>
but it looks like it's not ready yet.

Regards,

Mick
