### ISSUE TITLE
"Quit Seashore" disabled

### ISSUE THREAD

**Issue by Tricky1975** [robaho/seashore#4]
![image](https://user-images.githubusercontent.com/11202073/32908046-a518ac02-cb02-11e7-94b4-9e66ebeb0fb2.png)

I had no open pictures anymore when I saw this. In the dock I can still select the "Quit" feature, but doing so will lead to an ignored request.

In the end I could only use one method to quit SeaShore

![image](https://user-images.githubusercontent.com/11202073/32908133-f2b8799c-cb02-11e7-9440-f49cd869908e.png)

Not the most ideal method, but still...

Well, I'm not whining, I am very very grateful you brought this fantastic tool back from the dead. ;)

**Comment by robaho** [comment]
Can you produce the issue on demand ? Was there something you did just prior? Not a lot to go on...

**Comment by robaho** [comment]
Also, in the future, if it happens again, you can use the 'activity monitor' and do a 'sample' of the process and attach that here. That would help.

**Comment by Tricky1975** [comment]
I shall use the activity monitor next time, when it comes to my course of actions, I can sumarize it easily.

1. I just installed SeaShore from the latest release here on GitHub
2. I created a new picture
3. Just to test if it works I drew some random lines and used the fill feature to make a nice piece of “modern art”
4. “Used Quit", I was promted to save and I did (in xcf format)
5. Had to press the closure button again (I vaguely remember this was already an issue in the original SeaShore)
6. And then my Quit feature was disabled (and that never happened in the original Seashore).

I hope this sumary is already helpful

**Comment by robaho** [comment]
I was able to reproduce. I'll try to fix it when I get a chance. In the meantime, If you just 'save' first, then 'quit' it seems to work fine.

**Comment by Tricky1975** [comment]
Thank you ;)
I will do that...

**Comment by robaho** [comment]
fixed with 0.6.3

**Comment by Tricky1975** [comment]
Thank you very much :)
