### ISSUE TITLE
unable to select any tools other than rect select

### ISSUE THREAD

**Issue by ladobz** [robaho/seashore#43]
Hi there, just downloaded new version from app store. I cannot seem to use any tools except the rectangle select tool. When I select any other tool, the icon is greyed as if selected but only the rectangle select is active. Any advice? Thanks!

**Comment by robaho** [comment]
@ladobz I’m so sorry to hear that. I had that issue once during development and could not repeat it, so I figured it was a temporary bug that was fixed during the refactoring. 

What version of OS X are you running? Also, can you check the console log to see if there are any messages you can paste here? Thanks for your help.

**Comment by ladobz** [comment]
Hi Robert
Thanks for getting back to me
I’m running El Capitan 10.11.16
Installed and re-downloaded from the app store, rebooted laptop too but that hasn’t fixed it
Please find the console log attached (haven’t used console before, hope I’ve sent the right stuff). The message that seems to point to the issue is also below
Thanks again!

12/02/2019 08:43:53.568 Seashore[779]: -[NSSegmentedControl tagForSegment:]: unrecognized selector sent to instance 0x7f90bd017a30
12/02/2019 08:43:53.569 Seashore[779]: -[NSSegmentedControl tagForSegment:]: unrecognized selector sent to instance 0x7f90bd017a30
12/02/2019 08:43:53.573 Seashore[779]: (
0   CoreFoundation                      0x00007fff8ca62452 __exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff90e5273c objc_exception_throw + 48
2   CoreFoundation                      0x00007fff8cacc18d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x00007fff8c9d24c1 ___forwarding___ + 1009
4   CoreFoundation                      0x00007fff8c9d2048 _CF_forwarding_prep_0 + 120
5   Seashore                            0x0000000101b5ac94 Seashore + 269460
6   libsystem_trace.dylib               0x00007fff98edb07a _os_activity_initiate + 75
7   AppKit                              0x00007fff8bc1cdbd -[NSApplication sendAction:to:from:] + 460
8   AppKit                              0x00007fff8bc2ef12 -[NSControl sendAction:to:] + 86
9   AppKit                              0x00007fff8bc2ee3c __26-[NSCell _sendActionFrom:]_block_invoke + 131
10  libsystem_trace.dylib               0x00007fff98edb07a _os_activity_initiate + 75
11  AppKit                              0x00007fff8bc2ed99 -[NSCell _sendActionFrom:] + 144
12  AppKit                              0x00007fff8bc2ecfc -[NSSegmentedCell _sendActionFrom:] + 105
13  libsystem_trace.dylib               0x00007fff98edb07a _os_activity_initiate + 75
14  AppKit                              0x00007fff8bc2d3be -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2693
15  AppKit                              0x00007fff8bc2c574 -[NSSegmentedCell trackMouse:inRect:ofView:untilMouseUp:] + 1533
16  AppKit                              0x00007fff8bc2bae8 -[NSControl mouseDown:] + 669
17  AppKit                              0x00007fff8c1803c9 -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
18  AppKit                              0x00007fff8c1813ad -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
19  AppKit                              0x00007fff8bbc0539 -[NSWindow sendEvent:] + 517
20  AppKit                              0x00007fff8bb40a38 -[NSApplication sendEvent:] + 2540
21  AppKit                              0x00007fff8b9a7df2 -[NSApplication run] + 796
22  AppKit                              0x00007fff8b971368 NSApplicationMain + 1176
23  Seashore                            0x0000000101b1a854 Seashore + 6228


On 12 Feb 2019, at 00:35, robert engels <notifications@github.com<mailto:notifications@github.com>> wrote:


@ladobz<https://github.com/ladobz> I’m so sorry to hear that. I had that issue once during development and could not repeat it, so I figured it was a temporary bug that was fixed during the refactoring.

What version of OS X are you running? Also, can you check the console log to see if there are any messages you can paste here? Thanks for your help.

**Comment by robaho** [comment]
Thank you so much. It looks like I should be able to resolve it with this. Unfortunately not until the weekend. If you’re in a bind the earlier dmg for 2.2.0 may get you by available here in the releases section.

**Comment by ladobz** [comment]
Thank you Robert. I am using an earlier version at the moment. Hope it works out over the weekend

On 12 Feb 2019, at 19:41, robert engels <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you so much. It looks like I should be able to resolve it with this. Unfortunately not until the weekend. If you’re in a bind the earlier dmg for 2.2.0 may get you by available here in the releases section.

**Comment by robaho** [comment]
@ladobz This should be working correctly in version 2.4.0 which is available in releases and should be available in the app store shortly. Please test and report back. Thanks !

**Comment by robaho** [comment]
@ladobz did you by chance have a chance to test version 2.4.0 ?

**Comment by ladobz** [comment]
I had some trouble opening the dmg earlier but have tried again and it works now, thank you!
Do you know when it will be on app store?

On 18 Feb 2019, at 23:02, robert engels <notifications@github.com<mailto:notifications@github.com>> wrote:


@ladobz<https://github.com/ladobz> did you by chance have a chance to test version 2.4.0 ?

**Comment by robaho** [comment]
I just received notice that v 2.4.0 is available in the App Store. I am going to close this issue.

**Comment by robaho** [comment]
Sometimes it takes a while to show up in your App Store though... just make sure you see version 2.4.0

**Comment by ladobz** [comment]
Hi Robert,
I’ve been trying to use the channels today but when I try to copy and paste into the alpha channel of a layer, seashore either crashes or the image that is pasted is incorrect (a small, fuzzy area is all I get).
I’m running El Capitan 10.11.16
I have attached some info from console, including the crash report.
Can you help?
Thank you.

**Comment by robaho** [comment]
@ladobz please open another bug for this issue, including the supporting crash logs, etc.

**Comment by robaho** [comment]
@ladobz see issue #56
