### ISSUE TITLE
SVG Importer does not support Xcode V10.1?

### ISSUE THREAD

**Issue by YongLiedu** [robaho/seashore#44]
Hi, how can I compile the plug-in SVG Importer using Xcode v10.1?

![image](https://user-images.githubusercontent.com/24246903/52830627-8018fa80-310c-11e9-80a9-7cc2afd00150.png)

**Comment by robaho** [comment]
I don’t know and haven’t tried. The next release has built in svg loading so the plugin is not required.

**Comment by YongLiedu** [comment]
Great! Thank you very much.

**Comment by robaho** [comment]
This should work correctly in version 2.4.0 which is available in releases, and should be available in the app store shortly.
