### ISSUE TITLE
Greyscale jpg opening as alpha channel only

### ISSUE THREAD

**Issue by Ivgoneriding** [robaho/seashore#47]
I am trying to open a digital radiograph image, which is greyscale and i only see the alpha channel. If I select primary channel only, I see a black square with nothing else in it: 
![Screen Shot 2019-04-04 at 19 31 06](https://user-images.githubusercontent.com/49288040/55579467-344c0000-5710-11e9-859c-d908295395d1.png)
Image should look like this: 
![Screen Shot 2019-04-04 at 19 31 29](https://user-images.githubusercontent.com/49288040/55579502-5180ce80-5710-11e9-97f1-78f893dfcca7.png)

This is a brand new install of Seashore. I have tried with a png of the same file, with the same results.

**Comment by robaho** [comment]
Can you attach the image to this issue.  I think you can protect it if need be or send it to me directly.

**Comment by Ivgoneriding** [comment]
Original and png export attached




Kind regards

Vikki






Vikki Fear DEP MEPA
ep@vikkifear.co.uk
07986711310




On 4 Apr 2019, at 19:48, robert engels <notifications@github.com> wrote:

Can you attach the image to this issue. I think you can protect it if need be or send it to me directly.

**Comment by robaho** [comment]
I don’t think you can reply to the email with the attachments. You need to comment in the incident on GitHub and attach them there.

**Comment by robaho** [comment]
I say this because I think the image in the original comment may be a screenshot? If it is the actual image just let me know.

**Comment by Ivgoneriding** [comment]
The image is a screenshot. I'll try adding it later. I don't have my github password to hand.

⁣Regards,

Vikki 


Vikki Fear  DEP MEPA
07986711310
ep@vikkifear.co.uk​


-------- Original Message --------

**Comment by Ivgoneriding** [comment]
![20190403 LFL](https://user-images.githubusercontent.com/49288040/55588435-aa0e9680-5725-11e9-950a-a99aef21d3bf.jpg)
Original image

**Comment by robaho** [comment]
Great. That should be fine.

**Comment by robaho** [comment]
That image opens fine for me. Can you try downloading it from here, and see if it opens for you ? It may be that github corrected it when attaching. You can try sending the image to me directly at robaho@me.com

**Comment by Ivgoneriding** [comment]
I get the same issue when downloading the file from here: 
![Screen Shot 2019-04-05 at 09 58 09](https://user-images.githubusercontent.com/49288040/55616288-65b4e200-5789-11e9-9956-a4e7e45fb235.png)
I have emailed you the original file.

**Comment by robaho** [comment]
Hmm. It is working fine for me. I am going to ask others to open it - also if the community could try opening this image 

![](https://user-images.githubusercontent.com/49288040/55588435-aa0e9680-5725-11e9-950a-a99aef21d3bf.jpg)

and report back with OS version, etc. and if it failed or not, that would be helpful.

**Comment by Ivgoneriding** [comment]
Thanks.


-------- Original Message --------

**Comment by SimplyTheOther** [comment]
I can open it successfully from both inside Seashore and from Finder. The image appears to look exactly the same as it does on Github. 

I am using Seashore Version 2.4.0 (201902170) from the App Store and macOS Mojave 10.14.4.

**Comment by robaho** [comment]
@Ivgoneriding I’m beginning to think this is a problem specific to your setup. Do you know how to use ‘Console’ to inspect the logs? Maybe have that open while you try to open the image and see if it reports anything interesting? It could be that I broke something so that i5 doesn’t work on 10.11 and I am reviewing the code for that as well. Still trying...

**Comment by robaho** [comment]
@Ivgoneriding I've been able to duplicate the issue - it seems older versions of OSX cannot work with grayscale with alpha channels.

Which version of OSX are you using ?

**Comment by robaho** [comment]
@Ivgoneriding this is fixed in version 2.4.2 - it is available here in 'releases' and will be in the App Store soon
