### ISSUE TITLE
Is there a OS X or 10.6.8 or 10.7.5 version of SeaShore?

### ISSUE THREAD

**Issue by Navy-Brat** [robaho/seashore#48]
First off, I wanted to thank you all for your wonderful work on SeaShore. It's a real dedication. I'm sad though as I've been unable to run any of the new SeaShores (the 0.6.6 versions or 2.4.0) on my 2009 13" 2.13 Ghz White MacBook (Model #A1181) running either 10.7.5 and 10.6.8. It's 64-bit computer. Is there a version available other than 0.5.1? Thank you.

I downloaded seashore-bin-0.6.6.dmg from your site at https://sourceforge.net/projects/seashore/files/ but it gave me a "no mountable image" warning. Next, I downloaded the seashore-bin-0.6.6.hfs.dmg file from the same web address,  ran it, it bounced a couple of times on the dock, but would not load. Finally, I downloaded 2.4.0 from the mac app store and it installed, but would not run.

**Comment by robaho** [comment]
@Navy-Brat you're welcome. The 0.6.6.hfs.dmg is the version you need. The only thing I can suggest is to install that version (use Spotlight to make sure there are no Seashore.app instances anywhere on your machine first), and then if it fails to start, use the 'Console' to watch for any errors from Seashore and report them here and maybe there is something I can do.

I don't even think I can install 10.7.x on my hardware so it would be up to the community to help out.

**Comment by robaho** [comment]
@Navy-Brat actually, the version in the App Store 2.4.0 should work on 10.7.5. If it crashes, and you 'report failure' to developer I should be able to fix it. If not, again you'll need to use the console to record the errors as to why it is failing and paste them here.

**Comment by Navy-Brat** [comment]
Thanks Robaho. You're very kind.

To make it easier, let's take one at a time: Seashore 0.6.6hfs first.

On my OS X 10.7.5 MacBook, I removed  all instances of Seashore 0.5.1, 0.6.6 HFS, and 2.40 rebooted and downloaded a fresh copy of seashore-bin-0.6.6.hfs.dmg from your website: https://sourceforge.net/projects/seashore/files/v0.6.6%20-%20legacy%20version%20-%20before%2010.7/ I double-clicked the dmg, moved its contents to a folder I created in my Applications folder called Seashore 0.6.6hfs, ran  Console, and then ran Seashore and got the following messages on Console:

The first time I double-clicked it said:

4/22/19 12:37:27.181 AM	Seashore	Unable to load nib file: MainMenu, exiting
 
I never received that message again. The next time I double-clicked it said:

4/22/19 12:40:33.215 AM	xpchelper	restored permissions (100644 -> 100744) on /Users/navybrat/Library/Containers/app.seashore/Container.plist
4/22/19 12:40:33.471 AM	com.apple.launchd.peruser.501	([0x0-0x33033].app.seashore[436]) Exited with code: 1
 
And every time I double-clicked after that it said:

4/22/19 12:41:04.547 AM	com.apple.launchd.peruser.501	([0x0-0x34034].app.seashore[441]) Exited with code: 1

I hope this helps. Thank you all so much for your help. When we get this one Fixed , then we'll move on to Seashore 2.40. Thanks.

**Comment by robaho** [comment]
@Navy-Brat I am thinking you only have a 32 bit computer ? I am sorry then, there is no way for me to build & test - it is 64 bit only at this point. Please verify that is the case ?

**Comment by Navy-Brat** [comment]
No. As I mentioned, I have a 2009 13" 2.13 Ghz White MacBook (Model #A1181) running 10.7.5 with 2Gb of ram. It's 64-bit.

**Comment by robaho** [comment]
Ok. I am still working on getting access to a 10.7.5 install.

**Comment by Navy-Brat** [comment]
Thank you Mr. Engels. That's very kind of you.

Sincerely,

Steve Graanet
Marina43182@outlook.com<mailto:Marina43182@outlook.com>


On Apr 24, 2019, at 5:35 AM, robert engels wrote:


Ok. I am still working on getting access to a 10.7.5 install.

**Comment by robaho** [comment]
@Navy-Brat  version 2.4.1 available in the 'releases' should work on 10.7.5

I was able to install OSX 10.7.5 in a VM to figure out what the problem was.
