### ISSUE TITLE
Support for reading HEIC and HEIF image files

### ISSUE THREAD

**Issue by emclain** [robaho/seashore#52]
Apple's preferred image format is now HEIC (High-Efficiency Image Container - https://www.tomshardware.com/news/how-to-open-heic-file,36733.html) files rather than PNG or JPG.  In particular, iOS's camera app now uses this format by default, and macOS Photos and Preview can handle it natively.

It would be nice if Seashore could also read them natively.

**Comment by robaho** [comment]
fixed in 2.4.3. It supports reading and writing. The write compression works amazingly well. Only supported on OSX 10.13.4+. Also, only HEIC files, not HEIF.
