### ISSUE TITLE
Layer pane/sidebar colouration issue

### ISSUE THREAD

**Issue by SimplyTheOther** [robaho/seashore#53]
On my Mac (macOS Mojave 10.14.4 mid-2012 MacBook Pro), Seashore's layer pane background is black in both "light" mode and "dark mode". The old Seashore's wasn't, and I thought it might have been simply an aesthetic choice, but I noticed that your screenshot doesn't have this issue. I think you mentioned before that your computer didn't support dark mode, so that could be the root of it.

Here's a screenshot of Seashore in "light mode":
![Screen Shot 2019-05-10 at 8 29 32 pm](https://user-images.githubusercontent.com/19371469/57527752-11da8180-7363-11e9-9ce4-4908c118accc.png)
versus the screenshot on the readme:
![](https://raw.githubusercontent.com/robaho/seashore/master/doc/screenshot.png)

The layer displays themselves do not appear to be affected - it simply seems to be the colour of the background. For example, with several layers:
![Screen Shot 2019-05-10 at 8 39 02 pm](https://user-images.githubusercontent.com/19371469/57527987-a5ac4d80-7363-11e9-8853-6c477bfa2489.png)

Also, if I use my trackpad to scroll up inside the layers sidebar, it shows that there is white below the black. Similarly, if I scroll up, there's white on top of the sidebar. 
![Screen Shot 2019-05-10 at 9 07 31 pm](https://user-images.githubusercontent.com/19371469/57529646-fc1b8b00-7367-11e9-932e-5e29567abba7.png)
![Screen Shot 2019-05-10 at 9 09 01 pm](https://user-images.githubusercontent.com/19371469/57529653-0047a880-7368-11e9-954f-e8d3677b3592.png)

So yeah, while this does not impact functionality at all, it would be more aesthetically pleasing if it was fixed.

**Comment by robaho** [comment]
I agree, and am working on fixing. It only happens in Mojave - so hard for me to fix/debug.

**Comment by robaho** [comment]
@SimplyTheOther maybe you can help me out, if you use the painting tools, do the brushes/pencils appear properly in the 'recents' pane ?

**Comment by SimplyTheOther** [comment]
I'm not sure what the 'recents' pane is meant to show, but nothing appears for me after drawing with a brush, changing brush sizes and drawing with the new size, changing to pencil and drawing with that, changing brush to wood texture and drawing with it, changing back to pencil and drawing with the wood texture (or a colour from it or something), etc. 

I took a video to illustrate this with as many tools as I could use (attached as a zip because apparently videos aren't supported properly):

[SeashoreRecents.mp4.zip](https://github.com/robaho/seashore/files/3169784/SeashoreRecents.mp4.zip)

**Comment by robaho** [comment]
@SimplyTheOther thank you for the video. It confirms what I saw previously - not sure what is different on the machine where the original screenshots were taken - but I am in the process of installing a Mojave VM so I should be able to fix it.

**Comment by robaho** [comment]
fixed in 2.4.3
