### ISSUE TITLE
Font color selection doesn't work

### ISSUE THREAD

**Issue by RemiZajac** [robaho/seashore#58]
When selecting a font color other than the black default, the text stays black doesn't switch to the selected color. Version 2.4.4 (2019051701) running on Mac OS 10.12.6.

**Comment by robaho** [comment]
@RemiZajac This is working fine for me. Did you change the foreground color using the color chooser in the toolbar ? You have to ensure the last color change you made was the foreground - or the 'color chooser' from the font panel will be changing the background color instead.

Also, it only changes it in the content panel, not the text area.

The only other thing I can think was that maybe you were editing the alpha channel only?

Attach a screen shot showing everything, or better yet a video. :)

**Comment by RemiZajac** [comment]
Ha yes, works, forgot to change the foreground color...

________________________________
