### ISSUE TITLE
Dark Mode Control Missing

### ISSUE THREAD

**Issue by dakosek** [robaho/seashore#77]
I am running Version 2.4.9 (2019073001) and can't find a control for dark mode anywhere.  Where can I turn it on?  You need to add this information to the front page.

BTW... Great job on the updates!

Dan

**Comment by robaho** [comment]
Dark mode is only available when running Mojave or later. It is based on your OS setting.

**Comment by robaho** [comment]
Closing as there is nothing I can do... You need to have Mojave for 'dark mode' - there's a chance I could manually add it, but it's a lot of work...
