### ISSUE TITLE
Weird grid (too small) when moving a layer after zooming in

### ISSUE THREAD

**Issue by lfom** [robaho/seashore#79]
Hello! It's me again, with another bug report.

Since a while back (I don't know exactly when) the yellow grid shown when moving a layer has a space so small that it's hard to see the image/background. It only happens after you zoom in a little (therefor it makes really hard to work with small images). This happens in the latest version as well (downloaded today from AppStore). Please see the attached screenshots, with and without zoom.

Regards

![Screen Shot 2019-08-28 at 21 46 30](https://user-images.githubusercontent.com/15659999/63905962-5199a780-c9ec-11e9-9856-a3c13050b559.png)
![Screen Shot 2019-08-28 at 21 46 38](https://user-images.githubusercontent.com/15659999/63905961-5199a780-c9ec-11e9-9d1c-84e8b74356a1.png)

**Comment by robaho** [comment]
I am able to reproduce. I will look into it. Probably not until the weekend. Thanks for reporting.

**Comment by robaho** [comment]
fixed in 2.4.11. The path from the zoom pixel guides was not being reset for the position guides. It only occurred when the zoom was greater than 2
