### ISSUE TITLE
Building guide

### ISSUE THREAD

**Issue by sonique6784** [robaho/seashore#8]
Hi, thanks for keeping seashore working in recent MacOS version.
I couldn’t compile the project because of nib files missing.
CIVortex, CIStarshine, CIMonochrome, CIExposure, CIParallelogramTile, CIDisplacementDistortion
Actually there is no Base.lproj Into these folders.

I also got seashore.h not found from CI*.h

I believe I’m doing something wrong by couldn’t find a build guide

I’m using high Sierra and Xcode 10.0
And opening seashore/seashore.xcodeproj

Thanks for your help

**Comment by robaho** [comment]
I will add and commit all of my project files. I am building under XCode 10.1

**Comment by robaho** [comment]
I am in the process of fixing issue #1, but all of the code and project files have been posted to git.

**Comment by robaho** [comment]
Also, as far as a build guide, I'm not even a Mac developer... The XCode system is horrible IMO, and is continually changing. I just hope that the automatic conversion works, and cross my fingers - on every release.

Not to mention the APIs being continually deprecated... It's a very difficult platform to develop for - remind me of M$ in the 2000's...

**Comment by sonique6784** [comment]
Hi Rob,
Thank you for your help. I managed to build it. 
I had to add SeaPlugins.h file into CIUnsharpMask and CINoiseReduction xcodeproj/Classes/

And now it’s compiling fine. I will open a PR when I get home.
