### ISSUE TITLE
Cannot export as TIFF?

### ISSUE THREAD

**Issue by RemiZajac** [robaho/seashore#80]
Export XCF as JPEG works, but I'm getting an error when exporting as TIFF: 

        "The document cannot be exported as TIFF. The file doesn't exists."

![Screen Shot 2019-09-25 at 11 34 11](https://user-images.githubusercontent.com/51056148/65631399-4e162380-df8c-11e9-8ebe-a0275bf50aad.png)

**Comment by robaho** [comment]
fixed in 2.4.12

The bitmap image settings were incorrect so the file could not be saved.

**Comment by RemiZajac** [comment]
Works, thanks Robert.


________________________________
