### ISSUE TITLE
Straight Line modifier not working

### ISSUE THREAD

**Issue by hruettimann** [robaho/seashore#82]
The "Draw Straight Lines" modifier for Pencil or Brush doesn't seem to make a difference. I engaged the modifier using the keyboard shortcut with the shift key and shift+ctrl key combination, but also selecting the modifier with the pulldown menu didn't make any difference. I am using Seashore on macOS Mojave 10.14.6, maybe the added security features in Mojave are somehow involved in this?

**Comment by robaho** [comment]
I will look into it this evening. Thanks for reporting.

**Comment by robaho** [comment]
OK, it is working fine for me. I think you might not understand how it works (it works differently than many drawing apps). You use the modifier - click a point, then click another point - and it will draw a straight line between them. Most often you want to use the 45 degree option, as that will draw a line closest to the 45 degree increment (so easiest to draw horizontal and vertical lines).

Re-open if you have any questions.

**Comment by hruettimann** [comment]
Good morning Robert Engels

Sorry, you are right of course, it is working perfectly. 
I am just so used to the "snapping behaviour" commonly used by other graphic or video applications that it just didn't occur to me that it could be implemented differently.
Now I know!

All the best, 
Hannes
