### ISSUE TITLE
Won't close for logout.

### ISSUE THREAD

**Issue by ARobinW** [robaho/seashore#83]
MacOS High Sierra v 10.13.6 on iMac 21.5-inch , Late 2009.
"An app has interrupted logout.
  To continue logging out, click to Try Again."
Does not appear as Seashore in Activity Monitor, so tough to decide what to do, apart from switch off and switch on again !

**Comment by ARobinW** [comment]
However, it was really nice to use and did the job I needed it for, which I could not do in Preview.
Nice to have - switch off afterwards !

**Comment by robaho** [comment]
I am pretty sure it is not Seashore if it is not listed in the Activity Monitor. This would be the only ever report of this. If it was Seashore, are you certain it did not have a dialog up (maybe asking you to save changes?)

**Comment by robaho** [comment]
Maybe you can provide additional details - like if it is not appearing in Activity Monitor, why are you certain it is Seashore? Thanks for your help.

**Comment by ARobinW** [comment]
Because the logo appears in the window of running apps on Cmd+Tab, as attached.
![Seashore-present](https://user-images.githubusercontent.com/56200385/66260271-4f2d2900-e7b4-11e9-9d28-62a274b1d51a.png)
When you click on it, the Seashore menu appears on the menu bar.  It works too, I can e.g. open recent files.  However, File > Quit is greyed out.

**Comment by ARobinW** [comment]
![NoSeashore-in-monitor](https://user-images.githubusercontent.com/56200385/66260311-f27e3e00-e7b4-11e9-8b76-2ca8b9f18d07.png)
Here's the relevant part of the Activity Monitor in Process Name order.

**Comment by ARobinW** [comment]
OK, I'll switch off until tomorrow
Thanks for your feedback
Regards
Robin

**Comment by robaho** [comment]
Can you possibly look in the 'Console' application and see if Seashore is generating any errors? If you just open Seashore and don't do anything, can you use quit? Under the 'window' menu in Seashore, do you see any open files listed? Thanks for your help.

**Comment by ARobinW** [comment]
Switched back on. Nothing in Console for search 'Seashore'.
Launch Seashore, Console now says:
"default	21:56:21.157479 +0100	launchservicesd	CHECKIN:0x0-0x34034 939 app.seashore
default	21:56:21.657544 +0100	Seashore	Could not find image named 'warning'.
default	21:56:31.238114 +0100	Seashore	LSExceptions shared instance invalidated for timeout.
default	21:56:31.617988 +0100	Seashore	Loading plugins from /Applications/Seashore.app/Contents/PlugIns
default	21:56:31.619138 +0100	Seashore	checking plugin Alpha2Gray.bundle
default	21:56:31.619386 +0100	Seashore	checking plugin Brightness.bundle
default	21:56:31.619578 +0100	Seashore	checking plugin Checkerboard.bundle
default	21:56:31.619761 +0100	Seashore	checking plugin CMYK.bundle
default	21:56:31.619950 +0100	Seashore	checking plugin Gaussian.bundle
default	21:56:31.620141 +0100	Seashore	checking plugin Greyscale.bundle
default	21:56:31.620331 +0100	Seashore	checking plugin HorizStripes.bundle
default	21:56:31.620516 +0100	Seashore	checking plugin HSV.bundle
default	21:56:31.620693 +0100	Seashore	checking plugin Invert.bundle
default	21:56:31.620874 +0100	Seashore	checking plugin Median.bundle
default	21:56:31.621055 +0100	Seashore	checking plugin Pixellate.bundle
default	21:56:31.621233 +0100	Seashore	checking plugin Posterize.bundle
default	21:56:31.621416 +0100	Seashore	checking plugin Random.bundle
default	21:56:31.621593 +0100	Seashore	checking plugin Sepia.bundle
default	21:56:31.621769 +0100	Seashore	checking plugin Sharpen.bundle
default	21:56:31.621959 +0100	Seashore	checking plugin Threshold.bundle
default	21:56:31.622147 +0100	Seashore	checking plugin VertStripes.bundle
default	21:56:31.622328 +0100	Seashore	checking plugin AffineTile+.bundle
default	21:56:31.622540 +0100	Seashore	checking plugin AutoEnhance+.bundle
default	21:56:31.622746 +0100	Seashore	checking plugin Bloom+.bundle
default	21:56:31.622949 +0100	Seashore	checking plugin Brightness+.bundle
default	21:56:31.623145 +0100	Seashore	checking plugin Bump+.bundle
default	21:56:31.623343 +0100	Seashore	checking plugin Checkerboard+.bundle
default	21:56:31.623540 +0100	Seashore	checking plugin CircleSplash+.bundle
default	21:56:31.623749 +0100	Seashore	checking plugin CircularScreen+.bundle
default	21:56:31.623973 +0100	Seashore	checking plugin CircularWrap+.bundle
default	21:56:31.624189 +0100	Seashore	checking plugin CMYKHalftone+.bundle
default	21:56:31.624409 +0100	Seashore	checking plugin Crystallize+.bundle
default	21:56:31.624624 +0100	Seashore	checking plugin DisplacementDistortion+.bundle
default	21:56:31.624843 +0100	Seashore	checking plugin DotScreen+.bundle
default	21:56:31.625051 +0100	Seashore	checking plugin Edges+.bundle
default	21:56:31.625254 +0100	Seashore	checking plugin EdgeWork+.bundle
default	21:56:31.625463 +0100	Seashore	checking plugin Exposure+.bundle
default	21:56:31.625679 +0100	Seashore	checking plugin FalseColor+.bundle
default	21:56:31.625880 +0100	Seashore	checking plugin GammaAdjust+.bundle
default	21:56:31.626082 +0100	Seashore	checking plugin Gaussian+.bundle
default	21:56:31.626266 +0100	Seashore	checking plugin GlassDistortion+.bundle
default	21:56:31.626465 +0100	Seashore	checking plugin GlassLozenge+.bundle
default	21:56:31.626678 +0100	Seashore	checking plugin Gloom+.bundle
default	21:56:31.626869 +0100	Seashore	checking plugin HatchedScreen+.bundle
default	21:56:31.627083 +0100	Seashore	checking plugin Hole+.bundle
default	21:56:31.627270 +0100	Seashore	checking plugin HorizStripes+.bundle
default	21:56:31.627450 +0100	Seashore	checking plugin Invert+.bundle
default	21:56:31.627626 +0100	Seashore	checking plugin Kaleidoscope+.bundle
default	21:56:31.627831 +0100	Seashore	checking plugin LenticularHalo+.bundle
default	21:56:31.628049 +0100	Seashore	checking plugin LineScreen+.bundle
default	21:56:31.628252 +0100	Seashore	checking plugin Median+.bundle
default	21:56:31.628411 +0100	Seashore	checking plugin Monochrome+.bundle
default	21:56:31.628589 +0100	Seashore	checking plugin MotionBlur+.bundle
default	21:56:31.628780 +0100	Seashore	checking plugin NoiseReduction+.bundle
default	21:56:31.628972 +0100	Seashore	checking plugin OpTile+.bundle
default	21:56:31.629165 +0100	Seashore	checking plugin ParallelogramTile+.bundle
default	21:56:31.629357 +0100	Seashore	checking plugin PerspectiveTile+.bundle
default	21:56:31.629549 +0100	Seashore	checking plugin PerspectiveTransform+.bundle
default	21:56:31.629754 +0100	Seashore	checking plugin Pinch+.bundle
default	21:56:31.629932 +0100	Seashore	checking plugin Pixellate+.bundle
default	21:56:31.630091 +0100	Seashore	checking plugin Pointillize+.bundle
default	21:56:31.630286 +0100	Seashore	checking plugin Posterize+.bundle
default	21:56:31.630446 +0100	Seashore	checking plugin Random+.bundle
default	21:56:31.630614 +0100	Seashore	checking plugin Sepia+.bundle
default	21:56:31.630788 +0100	Seashore	checking plugin Sharpen+.bundle
default	21:56:31.630952 +0100	Seashore	checking plugin SpotLight+.bundle
default	21:56:31.631139 +0100	Seashore	checking plugin Starshine+.bundle
default	21:56:31.631298 +0100	Seashore	checking plugin Sunbeams+.bundle
default	21:56:31.631458 +0100	Seashore	checking plugin TorusLens+.bundle
default	21:56:31.631619 +0100	Seashore	checking plugin TriangleTile+.bundle
default	21:56:31.631794 +0100	Seashore	checking plugin Twirl+.bundle
default	21:56:31.631953 +0100	Seashore	checking plugin UnsharpMask+.bundle
default	21:56:31.632132 +0100	Seashore	checking plugin VertStripes+.bundle
default	21:56:31.632288 +0100	Seashore	checking plugin Vortex+.bundle
default	21:56:31.632456 +0100	Seashore	checking plugin WhitePointAdjust+.bundle
default	21:56:31.632637 +0100	Seashore	checking plugin ZoomBlur+.bundle
default	21:57:08.567431 +0100	Seashore	Loading plugins from /Users/robin/Library/Containers/app.seashore/Data/Library/Application Support/Seashore/PlugIns
error	21:57:11.099398 +0100	Seashore	        AEGetDescData of non-desc type 'reco' not a good idea
default	21:57:11.521751 +0100	Seashore	-[NSDocumentController openUntitledDocumentOfType:andDisplay:error:] failed during state restoration. Here's the error:
Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened."
"

**Comment by ARobinW** [comment]
However, as you suspected, Seashore > Quit Seashore is not greyed out to start with.
It's still OK after I Open Recent file.  Console now adds:
"default	21:59:10.808855 +0100	com.apple.WebKit.Networking	[26 <private> stream, pid: 806, url: https://github.com/robaho/seashore/issues/83/show_partial?partial=issues%2Fsidebar, tls] cancelled. Events:
default	21:59:59.451498 +0100	com.apple.WebKit.Networking	[28 <private> stream, pid: 806, url: https://github.com/robaho/seashore/issues/83/show_partial?partial=issues%2Ftitle&sticky=true, tls] cancelled
	[28.1.1 C8E52C31-E176-47D7-B8BB-E3BB3E940A7E <private>.49299<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 48.732s, DNS @0.128s took 0.002s, TCP @0.132s took 0.033s, TLS took 0.160s
	bytes in/out: 7965/1667, packets in/out: 8/3, rtt: 0.033s, retransmitted packets: 0, out-of-order packets: 0
default	22:00:17.108924 +0100	Seashore	Read options: 0 -- URL: <private> -- purposeID: D5CC7ABA-2C42-4844-9E63-83AEBAA68BBA -- claimID: 35C541EC-5489-4A8C-9E8A-62E6C949C5C9
default	22:00:17.111435 +0100	Seashore	Claim 35C541EC-5489-4A8C-9E8A-62E6C949C5C9 granted in client
default	22:00:17.111474 +0100	Seashore	Claim 35C541EC-5489-4A8C-9E8A-62E6C949C5C9 invoked in client
default	22:00:17.801162 +0100	Seashore	Adding presenter A0826D5F-9C30-49EA-96EB-5E6CAAF143D5 for URL: <private>
default	22:00:17.802578 +0100	Seashore	Adding presenter A0826D5F-9C30-49EA-96EB-5E6CAAF143D5 for URL: <private>
default	22:00:19.433433 +0100	Seashore	Making presenter A0826D5F-9C30-49EA-96EB-5E6CAAF143D5 observe change
default	22:00:24.411845 +0100	Seashore	CoreAnimation: failed to receive fence reply: 10004003
"

**Comment by ARobinW** [comment]
Closed file and Quit Seashore OK.
Console added:
"default	22:01:55.419604 +0100	Seashore	Removing presenter A0826D5F-9C30-49EA-96EB-5E6CAAF143D5
default	22:01:55.419714 +0100	Seashore	Removing presenter A0826D5F-9C30-49EA-96EB-5E6CAAF143D5
"
So it seems OK now from a user viewpoint.

**Comment by ARobinW** [comment]
Anyway, as mentioned, I am really impressed by the intuitive ease of use and the fact that I was struggling to join images together into a larger whole any other way (I have done it with access to PhotoShop, but that was quite a clunky procedure.)  Plus Seashore has fine control and layers.  It is really nice, thank you.
Of course I am also impressed by your speedy response !  I never experienced anything  as quick & efficient as that before.
Regards
Robin

**Comment by robaho** [comment]
@ARobinW thanks for the kind words -a bit of a lazy saturday here, so easy to respond - not always the case. It may be a specific file or order of operations that you do. If you can find the time and can narrow it down I would appreciate it. If you nor I can consistently cause it to happen (I can't...), it is very hard to fix.

**Comment by ARobinW** [comment]
OK Robert.

I'll look out for any repetition & send details if it occurs.
I had several other apps open & that will be the case again, so maybe... Hopefully not.

Regards

Robin
On Saturday, 5 October 2019 robert engels <reply@reply.github.com> wrote:

@ARobinW thanks for the kind words -a bit of a lazy saturday here, so easy to respond - not always the case. It may be a specific file or order of operations that you do. If you can find the time and can narrow it down I would appreciate it. If you nor I can consistently cause it to happen (I can't...), it is very hard to fix.

**Comment by esterluss** [comment]
I do have the same problem and I'm afraid that I'm not familiar with console etc. I mean, I know what that is but I'm just a user no coder. Seashore seems to be stuck in the 'create a new project' mode. It's in my dock, I see the icon and that it's active (blue dot) and when I click on it, it says that I should open a new or existing project. If I do, I can't quit seashore, it's greyed out. I can't even shut down my computer or install a mac os update because seashore can't be closed. Is there anything I can do to fix this or is there a fix I could download or update the software?
Cheers, klaus

**Comment by esterluss** [comment]
![Bildschirmfoto 2019-10-26 um 23 54 19](https://user-images.githubusercontent.com/57049320/67626464-fd743d80-f84b-11e9-9ef4-066a2d7f297c.png)
This is what I see.

**Comment by robaho** [comment]
@esterluss what version of OSX are you running? Did you install from the App Store ?

**Comment by robaho** [comment]
@esterluss also, if you open the file menu, and recents - is there anything there ? Can you open each of these files? Also - you should always be able to force-quit seashore by holding Control & Option, and clicking the icon in the dock, then choosing 'force quit'

**Comment by esterluss** [comment]
I run OS Mojave, 10.14.6 and I did install from the App store, yes. I worked on several files, I see them and I seem to be able to open them from recent files. I'll try the force quit option... and it worked, thanks, I did not know that. Best from Berlin, Klaus

**Comment by robaho** [comment]
@esterluss when the 'quit is disabled' can you use the 'window' menu and go through all of the windows to see if any have a dialog open? (this will cause quit to be disabled). Thanks.

**Comment by flemingm** [comment]
To help track down why, try open terminal and typing the follow two commands:

**ps -Axl | grep -i -e seashore -e PPID**
and 
**lsof  |grep -I seashore**

and copy the results into this chat.   It may point towards the issue.

fyi: 
grep filter out unwanted lines that don't match.
ps = list processes
lsof = list all open file for the process seashore.

**Comment by robaho** [comment]
I cannot reproduce this in 3.02
