### ISSUE TITLE
Enhancement: Non-contiguous paint bucket

### ISSUE THREAD

**Issue by Joseph-Y** [robaho/seashore#84]
I'd just like to request the feature for the paint bucket to fill non-contiguous pixels. 

I checked the Help guide to confirm this is not yet a feature--sorry if I'm missing something.

**Comment by robaho** [comment]
Hi @Joseph-Y, can you describe a little bit of what you want? There is a "tolerance" setting that controls how big an area is painted. You can also use the 'option' key to flood the entire layer/selection.

But, if I understand your ask correctly, it seems that in the end this would be implemented as "paint all pixels in the layer within a 'tolerance' of the clicked pixel'. Is this what you want ?

**Comment by Joseph-Y** [comment]
Yes, that's the request! Currently, if you draw a black circle on an empty
canvas and then paint bucket the white pixels outside the circle, the white
pixels inside the circle don't fill because the pixels aren't contiguous. Thank
you for your consideration.

And thank you for this awesome program Robert. I use it daily as a medical
student to make and edit diagrams.

**Comment by robaho** [comment]
@Joseph-Y One work-around that may be helpful - at least in the example of the circle - is to use the color select tool to select the circle, then use 'edit -> select inverse', then use the option key = paint bucket to perform a flood fill.

I'm looking into a code change to add an option to the color select tool to 'select all' which would do what you want.

**Comment by robaho** [comment]
fixed in 2.14.13. I added an options to the 'color select wand', to 'select all regions'. So you can use this, then use the 'flood fill' with the 'bucket tool' to do what you want. This is more versatile than only adding the option to the bucket fill. @Joseph-Y

**Comment by Joseph-Y** [comment]
Thank you so much again Robert. You rock.

**Comment by robaho** [comment]
@Joseph-Y should be available on the App Store now - let me know how it works.

**Comment by Joseph-Y** [comment]
Works beautifully. Thanks again. Is there a tip jar where I can buy you a
beer?

**Comment by robaho** [comment]
@Joseph-Y just leave a good review and rating on the app store :)
