### ISSUE TITLE
warn when quitting and bitmap images have multiple layers

### ISSUE THREAD

**Issue by yao2000** [robaho/seashore#91]
Hi,

I am posting this message to explain my comment on App Store. 

In Seashore every picture is opened as "Background" layer. I can create new layers and do some change on the new layer. But after saving file and closing Seashore, these layers are lost. Even I open the same file using Seashore, the modified picture is a whole part now and is "Background" again. 

For example, I may create a rectangle on one layer, and a circle on the 2nd layer. If layer info could be preserved, next time I want to modify the rectangle, I only need to modify the 1st layer. 
In current version, I need to extract rectangle first before modifying it.  

Thanks,
Yao

**Comment by robaho** [comment]
You need to save as an XCF file - this preserves the layers. The bitmap formats (png, tiff, jpg) do not support layers. 

Typically you work with XCF and then ‘export as’ a bitmap file. If you start by opening a bitmap file it assumes you want to save as a bit map. If layers are added it should warn you that layers will be lost when being saved (as a bitmap). Maybe the warning is not working.

**Comment by yao2000** [comment]
I could not find XCF file..I am using macOS 10.15.1 and Seashore Version 2.4.14 (2019113001)

<img width="748" alt="Screen Shot 2019-12-03 at 8 17 14 PM" src="https://user-images.githubusercontent.com/55400169/70050465-f938fe00-1609-11ea-9e87-a66de2dfe56a.png">

**Comment by yao2000** [comment]
Hi,

I just realized that GIMP image is XCF file...Maybe there are other people who do not know this..Is it possible to give warn when layer info would be lost when closing Seashore?

**Comment by robaho** [comment]
I will check on the warning. I will also change the label to GIMP/XCF. 

Again, best to use ‘export as’ for bitmap and always save to XCF. 

It is probably a problem for you since you are starting with a bit map file. You can also create a new XCF file then drag your file in as a layer.

**Comment by robaho** [comment]
I checked - it will warn you if you try to close the image. It doesn't warn you if you 'quit' and the some bitmap images have multiple layers.

**Comment by yao2000** [comment]
Thank you

**Comment by robaho** [comment]
fixed in 2.4.15 albeit slightly differently - when saving a document and it has layers and the current format does not support layers a warning will be issued
