### ISSUE TITLE
remember last chosen PDF import DPI

### ISSUE THREAD

**Issue by SolarpunkGnome** [robaho/seashore#92]
This may be a bit of weird case, so if it doesn't warrant a change I understand, but it would be nice to have either a default setting adjustment or a box to change the DPI setting for importing files to Seashore, particularly PDFs. 

I realize the idea is to keep the interface light/simple, so maybe this isn't compatible with the mission for the software. Right now, I have an XCF I use several times a week that needs to import PDFs at _300 DPI_. If there's an easy way to change it built into the software that I'm just missing, let me know.

**Comment by robaho** [comment]
I'll change it to remember the last import DPI, and retain this across restarts.

**Comment by SolarpunkGnome** [comment]
That would be splendid, however, I seem to be missing where one does change the import DPI to begin with. When I import, all I see is the file selection dialog. I may be missing something obvious, so I apologize for my ignorance.
![Screen Shot 2019-12-03 at 6 54 33 PM](https://user-images.githubusercontent.com/47646114/70100107-bf162f00-15fe-11ea-86a7-8281c05d4512.png)

**Comment by robaho** [comment]
After you open a pdf, the resolution dialog is displayed. The 'import' for a layer currently has it disabled, and I'm fixing it there too.

**Comment by SolarpunkGnome** [comment]
Ah, OK. Thank you very much! :)

**Comment by robaho** [comment]
fixed in 2.4.15
